(() => {
  "use strict";
  const CONFIG=window.TKB_HS_CONFIG||{};
  const DAYS=[{key:"mon",label:"Thứ Hai",short:"T2"},{key:"tue",label:"Thứ Ba",short:"T3"},{key:"wed",label:"Thứ Tư",short:"T4"},{key:"thu",label:"Thứ Năm",short:"T5"},{key:"fri",label:"Thứ Sáu",short:"T6"},{key:"sat",label:"Thứ Bảy",short:"T7"}];
  const SESSIONS=["Sáng","Chiều"], PREFIX="tkb_hs_lhp_v2:";
  const state={classes:Object.create(null),times:{Sáng:[],Chiều:[]},blocks:[],selected:"",activeDay:"",mode:"live",updatedAt:"",notes:Object.create(null),noteKey:"",deferredPrompt:null,toastTimer:0};
  const el={};
  document.addEventListener("DOMContentLoaded",init);
  function init(){collect();setupTheme();setupEvents();setupClock();setupInstall();registerSW();loadData(false);}
  function collect(){["live-clock-text","theme-button","home-link","class-search","class-search-count","class-select","refresh-button","share-button","install-button","calendar-button","image-button","print-button","data-status","current-period","current-period-title","current-period-detail","loading-view","error-view","error-message","retry-button","schedule-view","workspace-title","schedule-meta","desktop-schedule","day-tabs","day-panel","schedule-note","schedule-note-text","capture-area","toast","note-dialog","note-title","note-context","note-text","note-close","note-delete","note-save"].forEach(id=>el[toCamel(id)]=document.getElementById(id));}
  function setupEvents(){el.homeLink.href=CONFIG.homeUrl||"https://www.hoclieuso.id.vn/";el.themeButton.onclick=toggleTheme;el.classSearch.oninput=populateClasses;el.classSelect.onchange=()=>selectClass(el.classSelect.value);el.refreshButton.onclick=()=>loadData(true);el.retryButton.onclick=()=>loadData(true);el.shareButton.onclick=share;el.printButton.onclick=()=>print();el.calendarButton.onclick=exportCalendar;el.imageButton.onclick=downloadImage;el.noteSave.onclick=saveNote;el.noteDelete.onclick=deleteNote;el.noteDialog.onclick=e=>{if(e.target===el.noteDialog)el.noteDialog.close();};}
  function setupTheme(){let saved=readLocal(PREFIX+"theme");document.documentElement.classList.toggle("dark",saved?saved==="dark":matchMedia("(prefers-color-scheme: dark)").matches);}
  function toggleTheme(){const dark=document.documentElement.classList.toggle("dark");writeLocal(PREFIX+"theme",dark?"dark":"light");}
  function setupClock(){const tick=()=>{const now=new Date();el.liveClockText.textContent=capitalize(new Intl.DateTimeFormat("vi-VN",{timeZone:zone(),weekday:"long",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(now));renderPeriod(now);};tick();setInterval(tick,1000);}
  function setupInstall(){window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredPrompt=e;el.installButton.hidden=false;});el.installButton.onclick=async()=>{if(state.deferredPrompt){await state.deferredPrompt.prompt();state.deferredPrompt=null;el.installButton.hidden=true;}else toast("Mở menu trình duyệt rồi chọn “Thêm vào màn hình chính”.");};if(matchMedia("(display-mode: standalone)").matches)el.installButton.hidden=true;}
  function registerSW(){if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));}
  async function loadData(force){show("loading");busy(true);try{let result=!force?readCache():null;if(result){state.mode="cache";}else{try{result=await request();state.mode="live";writeCache(result);}catch(error){result=readCache(true);if(!result)throw error;state.mode="offline";}}const timetable=parseClasses(result.rows),time=parseTimes(result.timeRows);state.classes=timetable;state.times=time.times;state.blocks=time.blocks;state.updatedAt=result.updatedAt||"";try{state.notes=JSON.parse(readLocal(PREFIX+"notes")||"{}")||{};}catch{state.notes={};}populateClasses();const query=new URLSearchParams(location.search).get("class");const saved=readLocal(PREFIX+"class");const first=Object.keys(state.classes).sort(natural)[0];selectClass(state.classes[query]?query:state.classes[saved]?saved:first,false);renderStatus();}catch(error){showError(error.message||"Không kết nối được nguồn dữ liệu.");}finally{busy(false);}}
  async function request(){const url=new URL(CONFIG.apiUrl);url.searchParams.set("action","studentOnly");url.searchParams.set("t",Date.now());const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{cache:"no-store",credentials:"omit",signal:controller.signal});if(!response.ok)throw new Error("Máy chủ trả lỗi "+response.status+".");const payload=await response.json();if(!payload.success)throw new Error(payload.message||"API báo lỗi.");if(normalize(payload.source)!=="tkbhocsinh"||normalize(payload.timeSource)!=="thoigianbieu")throw new Error("Apps Script chưa có nhánh studentOnly đọc TKBHocSinh và ThoiGianBieu.");return payload;}catch(error){if(error.name==="AbortError")throw new Error("Kết nối quá 20 giây. Vui lòng thử lại.");throw error;}finally{clearTimeout(timer);}}
  function parseClasses(rows){if(!Array.isArray(rows))throw new Error("TKBHocSinh không đúng cấu trúc.");const hi=rows.slice(0,10).findIndex(r=>r.map(normalize).includes("lop")&&r.map(normalize).includes("tiet")&&r.map(normalize).includes("buoi"));if(hi<0)throw new Error("TKBHocSinh thiếu cột Lớp, Buổi hoặc Tiết.");const h=rows[hi].map(normalize),col=(...v)=>h.findIndex(x=>v.includes(x)),ci=col("lop"),cs=col("buoi"),cp=col("tiet"),ct=col("gvcn","giao vien chu nhiem"),cn=col("ghi chu"),dayCols=DAYS.map((d,i)=>col(normalize(d.label),"thu "+(i+2),"t"+(i+2)));if(dayCols.some(i=>i<0))throw new Error("TKBHocSinh thiếu cột thứ trong tuần.");const out=Object.create(null),occupied=new Set();let cls="",session="";rows.slice(hi+1).forEach((r,k)=>{const raw=clean(r[ci]);if(raw&&raw!==cls){cls=raw;session="";}if(!cls)return;if(!out[cls]){out[cls]={id:cls,title:"Lớp "+cls,teacher:"",note:"",schedule:{}};SESSIONS.forEach(s=>{out[cls].schedule[s]={};for(let p=1;p<=5;p++)out[cls].schedule[s][p]=Object.fromEntries(DAYS.map(d=>[d.key,""]));});}const item=out[cls];if(ct>=0&&clean(r[ct]))item.teacher=clean(r[ct]);if(cn>=0&&clean(r[cn]))item.note=clean(r[cn]);const marker=normalize(r[cs]);if(marker.startsWith("ghi chu")){item.note=clean(r[cs]).replace(/^ghi\s*chú\s*:?\s*/i,"");return;}if(marker==="sang")session="Sáng";else if(marker==="chieu")session="Chiều";else if(marker)throw new Error("Sai buổi ở dòng "+(hi+k+2)+".");const pText=normalize(r[cp]);if(!pText)return;const m=pText.match(/^(?:tiet\s*)?([1-5])$/);if(!m||!session)throw new Error("Sai buổi/tiết ở dòng "+(hi+k+2)+".");const p=+m[1];dayCols.forEach((dc,i)=>{const value=clean(r[dc]),key=JSON.stringify([cls,session,p,DAYS[i].key]);if(occupied.has(key)&&item.schedule[session][p][DAYS[i].key]!==value)throw new Error("Trùng ô khác nội dung ở lớp "+cls+".");occupied.add(key);item.schedule[session][p][DAYS[i].key]=value;});});if(!Object.keys(out).length)throw new Error("TKBHocSinh chưa có lớp.");return out;}
  function parseTimes(rows){if(!Array.isArray(rows))throw new Error("ThoiGianBieu không đúng cấu trúc.");const hi=rows.slice(0,10).findIndex(r=>r.map(normalize).includes("buoi")&&r.map(normalize).includes("tiet"));if(hi<0)throw new Error("ThoiGianBieu thiếu tiêu đề.");const h=rows[hi].map(normalize),cs=h.indexOf("buoi"),cp=h.indexOf("tiet"),cStart=h.findIndex(x=>x.includes("bat dau")),cEnd=h.findIndex(x=>x.includes("ket thuc"));if(cStart<0||cEnd<0)throw new Error("ThoiGianBieu thiếu giờ bắt đầu/kết thúc.");const times={Sáng:[],Chiều:[]},blocks=[];let session="";rows.slice(hi+1).forEach((r,k)=>{const mark=normalize(r[cs]);if(mark==="sang")session="Sáng";else if(mark==="chieu")session="Chiều";else if(mark)throw new Error("Sai buổi trong ThoiGianBieu.");if(!clean(r[cStart])&&!clean(r[cEnd]))return;if(!session)throw new Error("Thiếu buổi trong ThoiGianBieu.");const start=parseTime(r[cStart]),end=parseTime(r[cEnd]),label=normalize(r[cp]),m=label.match(/^(?:tiet\s*)?([1-5])$/),type=m?"period":/ra choi|giai lao/.test(label)?"break":"";if(!type)throw new Error("Sai tiết/ra chơi trong ThoiGianBieu dòng "+(hi+k+2)+".");const startM=toMinutes(start),endM=toMinutes(end);if(endM<=startM||(session==="Sáng"&&endM>720)||(session==="Chiều"&&startM<720))throw new Error("Giờ không khớp buổi "+session+".");const period=m?+m[1]:null;if(period){if(times[session][period-1])throw new Error("Trùng tiết "+period+" buổi "+session+".");times[session][period-1]=[start,end];}blocks.push({session,period,start,end,startM,endM,type});});SESSIONS.forEach(s=>{for(let p=1;p<=5;p++)if(!times[s][p-1])throw new Error("ThoiGianBieu thiếu tiết "+p+" buổi "+s+".");});blocks.sort((a,b)=>a.startM-b.startM);if(blocks.some((b,i)=>i&&b.startM<blocks[i-1].endM))throw new Error("Các khung giờ bị chồng nhau.");return{times,blocks};}
  function populateClasses(){const all=Object.keys(state.classes).sort(natural),q=normalize(el.classSearch.value).replace(/^lop\s*/,"").replace(/\s/g,""),filtered=all.filter(x=>normalize(x).replace(/\s/g,"").includes(q));el.classSelect.replaceChildren();const prompt=new Option(filtered.length?"Chọn trong "+filtered.length+" kết quả":"Không tìm thấy lớp","");prompt.disabled=!!filtered.length;prompt.selected=!filtered.includes(state.selected);el.classSelect.add(prompt);filtered.forEach(x=>el.classSelect.add(new Option("Lớp "+x,x)));if(filtered.includes(state.selected))el.classSelect.value=state.selected;el.classSearchCount.textContent=filtered.length+"/"+all.length+" lớp";}
  function selectClass(id,remember=true){if(!state.classes[id])return;state.selected=id;if(remember)writeLocal(PREFIX+"class",id);const url=new URL(location.href);url.searchParams.set("class",id);history.replaceState({},"",url);populateClasses();renderSchedule();renderPeriod(new Date());}
  function renderSchedule(){const data=state.classes[state.selected];show("schedule");el.workspaceTitle.textContent=data.title;el.scheduleMeta.replaceChildren();if(data.teacher)addPill("GVCN",data.teacher);renderDesktop(data);renderMobile(data);el.scheduleNote.hidden=!data.note;el.scheduleNoteText.textContent=data.note;}
  function renderDesktop(data){const table=document.createElement("table");table.className="schedule-table";const thead=document.createElement("thead"),tr=document.createElement("tr");["Buổi","Tiết",...DAYS.map(x=>x.label)].forEach((label,i)=>{const th=document.createElement("th");th.textContent=label;th.scope="col";if(i>1&&DAYS[i-2].key===currentDay())th.className="is-today";tr.append(th);});thead.append(tr);table.append(thead);SESSIONS.forEach(session=>{const body=document.createElement("tbody");for(let p=1;p<=5;p++){const row=document.createElement("tr");if(p===1){const th=document.createElement("th");th.scope="rowgroup";th.rowSpan=5;th.className="session-cell";th.textContent=session;row.append(th);}const ph=document.createElement("th");ph.scope="row";ph.className="period-cell";ph.textContent=p;row.append(ph);DAYS.forEach(day=>{const td=document.createElement("td");td.dataset.cell=[session,p,day.key].join("|");if(day.key===currentDay())td.classList.add("is-today");td.append(subjectChip(data.schedule[session][p][day.key],session,p,day.key));row.append(td);});body.append(row);}table.append(body);});el.desktopSchedule.replaceChildren(table);}
  function renderMobile(data){if(!DAYS.some(d=>d.key===state.activeDay))state.activeDay=currentDay()||DAYS[0].key;el.dayTabs.replaceChildren();el.dayPanel.replaceChildren();DAYS.forEach(day=>{const tab=document.createElement("button");tab.type="button";tab.className="day-tab";tab.textContent=day.short;tab.setAttribute("role","tab");tab.setAttribute("aria-label",day.label);tab.dataset.day=day.key;tab.onclick=()=>goDay(day.key,true);el.dayTabs.append(tab);const slide=document.createElement("section");slide.className="day-slide";slide.dataset.day=day.key;const title=document.createElement("div");title.className="mobile-day-title";title.innerHTML="<h3>"+day.label+"</h3>"+(day.key===currentDay()?'<span class="today-badge">Hôm nay</span>':"");slide.append(title);SESSIONS.forEach(session=>{const section=document.createElement("section");section.className="mobile-session";const h=document.createElement("h4");h.textContent="Buổi "+session.toLowerCase();section.append(h);let has=false;for(let p=1;p<=5;p++){const value=data.schedule[session][p][day.key];if(!value)continue;has=true;const row=document.createElement("div");row.className="mobile-period";row.dataset.cell=[session,p,day.key].join("|");const label=document.createElement("span");label.className="mobile-period-label";label.innerHTML="Tiết "+p+'<small>'+state.times[session][p-1].join("–")+"</small>";const val=document.createElement("div");val.className="mobile-period-value";val.append(subjectChip(value,session,p,day.key));row.append(label,val);section.append(row);}if(!has){const none=document.createElement("p");none.className="session-empty";none.textContent="Không có tiết học.";section.append(none);}slide.append(section);});el.dayPanel.append(slide);});el.dayPanel.onscroll=()=>{cancelAnimationFrame(state.scrollFrame);state.scrollFrame=requestAnimationFrame(()=>{const i=Math.max(0,Math.min(5,Math.round(el.dayPanel.scrollLeft/el.dayPanel.clientWidth)));if(DAYS[i].key!==state.activeDay){state.activeDay=DAYS[i].key;updateTabs();}});};requestAnimationFrame(()=>goDay(state.activeDay,false));}
  function goDay(key,smooth){state.activeDay=key;const i=DAYS.findIndex(d=>d.key===key);el.dayPanel.scrollTo({left:i*el.dayPanel.clientWidth,behavior:smooth&&!matchMedia("(prefers-reduced-motion: reduce)").matches?"smooth":"auto"});updateTabs();}
  function updateTabs(){el.dayTabs.querySelectorAll("button").forEach(b=>{const active=b.dataset.day===state.activeDay;b.classList.toggle("is-active",active);b.classList.toggle("is-today",b.dataset.day===currentDay());b.setAttribute("aria-selected",String(active));});}
  function subjectChip(value,session,p,day){const span=document.createElement("button");span.type="button";span.className=value?"subject-chip "+subjectClass(value):"subject-empty";span.textContent=value||"—";if(value){const key=noteKey(session,p,day),note=state.notes[key];span.title=note?"Ghi chú: "+note:"Thêm ghi chú cá nhân";span.onclick=()=>openNote(session,p,day,value);}else span.disabled=true;return span;}
  function openNote(session,p,day,value){state.noteKey=noteKey(session,p,day);el.noteTitle.textContent="Ghi chú: "+value;el.noteContext.textContent=DAYS.find(d=>d.key===day).label+" · Buổi "+session.toLowerCase()+" · Tiết "+p;el.noteText.value=state.notes[state.noteKey]||"";el.noteDelete.hidden=!state.notes[state.noteKey];el.noteDialog.showModal();el.noteText.focus();}
  function saveNote(){const text=el.noteText.value.trim();if(text)state.notes[state.noteKey]=text;else delete state.notes[state.noteKey];persistNotes();el.noteDialog.close();renderSchedule();toast("Đã lưu ghi chú trên thiết bị này.");}
  function deleteNote(){delete state.notes[state.noteKey];persistNotes();el.noteDialog.close();renderSchedule();toast("Đã xóa ghi chú.");}
  function persistNotes(){writeLocal(PREFIX+"notes",JSON.stringify(state.notes));}
  function renderPeriod(date){el.currentPeriod.classList.remove("is-active","is-holiday");document.querySelectorAll(".is-live-cell").forEach(x=>x.classList.remove("is-live-cell"));const c=clock(date);if(isSummer(c)){el.currentPeriodTitle.textContent="Nhà trường đang trong thời gian nghỉ hè";el.currentPeriodDetail.textContent="Từ ngày 01/6 đến hết ngày 04/9 · Tạm ẩn thông tin tiết học đang diễn ra.";el.currentPeriod.classList.add("is-holiday");return;}if(c.dayIndex<0){el.currentPeriodTitle.textContent="Hôm nay là Chủ nhật";el.currentPeriodDetail.textContent="Không có tiết học trong thời khóa biểu.";return;}if(!state.selected||!state.blocks.length)return;const block=state.blocks.find(x=>c.now>=x.startM&&c.now<x.endM);if(block){const remain=Math.max(1,Math.ceil(block.endM-c.now));if(block.type==="break"){el.currentPeriodTitle.textContent="Ra chơi · Buổi "+block.session.toLowerCase();el.currentPeriodDetail.textContent=block.start+"–"+block.end+" · Còn khoảng "+remain+" phút";return;}const day=DAYS[c.dayIndex].key,value=state.classes[state.selected].schedule[block.session][block.period][day];el.currentPeriodTitle.textContent="Đang diễn ra: Tiết "+block.period+" · Buổi "+block.session.toLowerCase();el.currentPeriodDetail.textContent=block.start+"–"+block.end+" · Còn khoảng "+remain+" phút"+(value?" · Lớp "+state.selected+": "+value:" · Lớp "+state.selected+" không có tiết học ở khung giờ này.");if(value){el.currentPeriod.classList.add("is-active");document.querySelectorAll('[data-cell="'+block.session+'|'+block.period+'|'+day+'"]').forEach(x=>x.classList.add("is-live-cell"));}return;}const next=state.blocks.find(x=>x.startM>c.now);if(next){el.currentPeriodTitle.textContent="Sắp tới: "+(next.type==="break"?"Ra chơi":"Tiết "+next.period)+" buổi "+next.session.toLowerCase();el.currentPeriodDetail.textContent="Bắt đầu lúc "+next.start+" · Còn khoảng "+Math.max(1,Math.ceil(next.startM-c.now))+" phút";}else{el.currentPeriodTitle.textContent="Đã kết thúc các tiết học trong ngày";el.currentPeriodDetail.textContent="Vuốt ngang hoặc chọn ngày khác để xem thời khóa biểu.";}}
  function exportCalendar(){const data=state.classes[state.selected],c=clock(),base=new Date(Date.UTC(c.year,c.month-1,c.day)),lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//LHP//TKB Hoc Sinh//VI","CALSCALE:GREGORIAN","METHOD:PUBLISH"];let count=0;for(let i=0;i<105;i++){const d=new Date(base);d.setUTCDate(base.getUTCDate()+i);const di=d.getUTCDay()-1;if(di<0||isSummer({month:d.getUTCMonth()+1,day:d.getUTCDate()}))continue;SESSIONS.forEach(s=>{for(let p=1;p<=5;p++){const value=data.schedule[s][p][DAYS[di].key];if(!value)continue;const [start,end]=state.times[s][p-1],asUTC=t=>new Date(d.getTime()+(toMinutes(t)-420)*60000);if(asUTC(end)<new Date())continue;lines.push("BEGIN:VEVENT","UID:"+encodeURIComponent(state.selected)+"-"+compact(asUTC(start))+"@tkb-lhp","DTSTART:"+compact(asUTC(start)),"DTEND:"+compact(asUTC(end)),"SUMMARY:"+ics(value+" (Lớp "+state.selected+")"),"DESCRIPTION:"+ics("Trường THCS Lê Hồng Phong · Tiết "+p+" buổi "+s),"END:VEVENT");count++;}});}if(!count){toast("Không có tiết học để xuất trong 15 tuần tới.");return;}lines.push("END:VCALENDAR");downloadBlob(new Blob([lines.join("\r\n")+"\r\n"],{type:"text/calendar;charset=utf-8"}),"TKB_LHP_Lop_"+state.selected+".ics");}
  async function downloadImage(){if(typeof html2canvas!=="function"){toast("Chưa tải được công cụ tạo ảnh.");return;}el.imageButton.disabled=true;try{const canvas=await html2canvas(el.scheduleView,{scale:2,backgroundColor:"#ffffff",useCORS:true,windowWidth:1100,onclone:doc=>{doc.documentElement.classList.remove("dark");const area=doc.getElementById("schedule-view");area.classList.add("capture-mode");area.style.width="1050px";}});const link=document.createElement("a");link.download="TKB_LHP_Lop_"+state.selected+".png";link.href=canvas.toDataURL("image/png");link.click();}catch{toast("Không tạo được ảnh. Vui lòng thử lại.");}finally{el.imageButton.disabled=false;}}
  async function share(){const data={title:"Thời khóa biểu "+(state.classes[state.selected]?.title||"học sinh"),text:"Xem thời khóa biểu học sinh Trường THCS Lê Hồng Phong",url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast("Đã sao chép liên kết.");}}catch(error){if(error.name!=="AbortError")toast("Không thể chia sẻ liên kết.");}}
  function renderStatus(){let t="Dữ liệu đã đồng bộ từ TKBHocSinh và ThoiGianBieu.";if(state.mode==="cache")t="Đang hiển thị bản đã lưu gần nhất để tải nhanh hơn.";if(state.mode==="offline")t="Mất kết nối — đang hiển thị bản đã lưu trên thiết bị.";if(state.updatedAt)t+=" Cập nhật: "+new Intl.DateTimeFormat("vi-VN",{timeZone:zone(),dateStyle:"short",timeStyle:"short"}).format(new Date(state.updatedAt))+".";el.dataStatus.textContent=t;el.dataStatus.classList.toggle("is-warning",state.mode==="offline");}
  function show(which){el.loadingView.hidden=which!=="loading";el.errorView.hidden=which!=="error";el.scheduleView.hidden=which!=="schedule";}
  function showError(message){show("error");el.errorMessage.textContent=message;el.dataStatus.textContent="";}
  function busy(value){el.refreshButton.disabled=value;el.classSelect.disabled=value;el.classSearch.disabled=value;el.refreshButton.classList.toggle("is-loading",value);}
  function writeCache(payload){writeLocal(PREFIX+"data",JSON.stringify({savedAt:Date.now(),payload}));}
  function readCache(stale=false){try{const item=JSON.parse(readLocal(PREFIX+"data")||"null");if(!item)return null;const age=Math.max(1,+CONFIG.cacheMinutes||30)*60000;if(!stale&&Date.now()-item.savedAt>age)return null;return item.payload;}catch{return null;}}
  function readLocal(k){try{return localStorage.getItem(k);}catch{return null;}}function writeLocal(k,v){try{localStorage.setItem(k,v);}catch{}}
  function addPill(label,value){const span=document.createElement("span");span.className="meta-pill";span.textContent=label+": ";const strong=document.createElement("strong");strong.textContent=value;span.append(strong);el.scheduleMeta.append(span);}
  function clock(date=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat("en-GB",{timeZone:zone(),year:"numeric",month:"2-digit",day:"2-digit",weekday:"short",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(date).map(x=>[x.type,x.value]));return{year:+p.year,month:+p.month,day:+p.day,dayIndex:["Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(p.weekday),now:+p.hour*60+ +p.minute+ +p.second/60};}
  function currentDay(){const i=clock().dayIndex;return i<0?"":DAYS[i].key;}function isSummer(c){const set=CONFIG.summerBreak||{},now=c.month*100+c.day;return now>=(+set.startMonth||6)*100+(+set.startDay||1)&&now<=(+set.endMonth||9)*100+(+set.endDay||4);}
  function parseTime(value){const s=clean(value).replace(/h/i,":"),m=s.match(/^(\d{1,2}):(\d{2})(?::\d{2})?\s*(AM|PM)?$/i);if(!m)throw new Error("Giờ không hợp lệ: "+s+".");let h=+m[1],min=+m[2];if(m[3])h=h%12+(m[3].toUpperCase()==="PM"?12:0);if(h>23||min>59)throw new Error("Giờ ngoài phạm vi: "+s+".");return String(h).padStart(2,"0")+":"+String(min).padStart(2,"0");}
  function subjectClass(v){const x=normalize(v);if(x.includes("ngu van")||/(^|\s)van(\s|$)/.test(x))return"subject-literature";if(x.includes("toan"))return"subject-math";if(["khtn","sinh","vat li","hoa hoc","cong nghe","tin"].some(t=>x.includes(t)))return"subject-science";if(["ngoai ngu","tieng anh"].some(t=>x.includes(t)))return"subject-language";if(["hdtn","chao co","shl","gddp","gdđp","gdtc","the duc","am nhac","mi thuat","my thuat"].some(t=>x.includes(normalize(t))))return"subject-activity";return"subject-default";}
  function noteKey(s,p,d){return JSON.stringify([state.selected,s,p,d]);}function clean(v){return String(v??"").trim();}function normalize(v){return clean(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d");}function toMinutes(v){return+v.slice(0,2)*60+ +v.slice(3,5);}function zone(){return CONFIG.timezone||"Asia/Ho_Chi_Minh";}function natural(a,b){return a.localeCompare(b,"vi",{numeric:true});}function toCamel(v){return v.replace(/-([a-z])/g,(_,x)=>x.toUpperCase());}function capitalize(v){return v.charAt(0).toUpperCase()+v.slice(1);}function compact(d){return d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");}function ics(v){return String(v).replace(/\\/g,"\\\\").replace(/\r?\n/g,"\\n").replace(/;/g,"\\;").replace(/,/g,"\\,");}function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}function toast(message){clearTimeout(state.toastTimer);el.toast.textContent=message;el.toast.hidden=false;state.toastTimer=setTimeout(()=>el.toast.hidden=true,3000);}
})();
