const BIOSPHERES = [
  {
    id:'can-gio', name:'Rừng ngập mặn Cần Giờ', unescoName:'Can Gio Mangrove',
    currentLocation:'TP. Hồ Chí Minh', unescoLocation:'Ho Chi Minh City', region:'Miền Nam', environment:'Đất ngập nước',
    type:['Rừng ngập mặn','Đất ngập nước','Ven biển'], year:2000, area:'75.740 ha', lat:10.52, lng:106.89,
    summary:'Hệ sinh thái rừng ngập mặn cửa sông – ven biển, là một “lá chắn xanh” quan trọng ở cửa ngõ phía nam TP. Hồ Chí Minh.',
    nature:'Rừng ngập mặn, bãi bùn, vùng triều, kênh rạch và sinh cảnh nước lợ tạo thành một hệ sinh thái chuyển tiếp giữa sông và biển.',
    people:'Sinh kế địa phương gắn với thủy sản, giữ rừng, dịch vụ và du lịch sinh thái; đời sống văn hóa mang đậm dấu ấn vùng sông nước ven biển.',
    role:'Bảo vệ bờ biển, giảm xói lở và tác động của bão; lưu giữ carbon; duy trì nguồn lợi thủy sản; hỗ trợ nghiên cứu và giáo dục môi trường.',
    challenge:'Đô thị hóa, du lịch, ô nhiễm nước, suy giảm sinh cảnh và tác động của biến đổi khí hậu.',
    highlight:'Khu dự trữ sinh quyển thế giới đầu tiên của Việt Nam.',
    source:'https://www.unesco.org/en/mab/can-gio-mangrove',
    image:{file:'Can Gio mangrove forest.jpg', author:'Tho nau', license:'CC BY-SA 3.0'},
    video:{id:'SxeVsQBEpM8', title:'Nam Bộ du ký: Khám phá rừng sác Cần Giờ', channel:'YouTube'}
  },
  {
    id:'red-river', name:'Châu thổ sông Hồng', unescoName:'Red River Delta',
    currentLocation:'Hưng Yên – Ninh Bình', unescoLocation:'Red River Delta coastal zone', region:'Miền Bắc', environment:'Đất ngập nước',
    type:['Đất ngập nước','Cửa sông','Rừng ngập mặn'], year:2004, area:'105.558 ha', lat:20.5354, lng:106.583,
    summary:'Không gian cửa sông – ven biển với bãi triều, rừng ngập mặn và vùng đất ngập nước có ý nghĩa đặc biệt đối với các loài chim di cư.',
    nature:'Bãi bồi, bãi triều, cửa sông, cồn cát và rừng ngập mặn được bồi đắp bởi phù sa sông Hồng; Vườn quốc gia Xuân Thủy là một vùng lõi tiêu biểu.',
    people:'Cộng đồng ven biển có sinh kế gắn với đánh bắt, nuôi trồng thủy sản, nông nghiệp và khai thác hợp lí tài nguyên vùng triều.',
    role:'Bảo tồn đất ngập nước ven biển, điểm dừng chân của chim di cư; bảo vệ bờ biển và hỗ trợ sinh kế vùng cửa sông.',
    challenge:'Biến đổi dòng chảy, ô nhiễm, nuôi trồng thủy sản, xói lở – bồi tụ và nước biển dâng.',
    highlight:'Một khu sinh quyển tiêu biểu để học về châu thổ, cửa sông, bãi triều và đường bay chim di cư.',
    source:'https://www.unesco.org/en/mab/red-river-delta',
    image:{file:'Landscape Xuan Thuy National Park.JPG', author:'Kristinvafranzi', license:'CC BY-SA 3.0'},
    video:{id:'KPqJR8YMvjs', title:'Độc đáo “ga chim” ở Vườn quốc gia Xuân Thủy', channel:'YouTube'}
  },
  {
    id:'cat-ba', name:'Cát Bà', unescoName:'Cat Ba',
    currentLocation:'TP. Hải Phòng', unescoLocation:'Hai Phong', region:'Miền Bắc', environment:'Biển – đảo',
    type:['Biển – đảo','Karst','Rừng'], year:2004, area:'26.241 ha', lat:20.8, lng:107.0,
    summary:'Quần đảo karst tiêu biểu ở miền Bắc, nơi rừng nhiệt đới, vùng triều, rừng ngập mặn và hệ sinh thái biển cùng tồn tại.',
    nature:'Địa hình karst bị biển xâm thực, hàng trăm đảo đá vôi, hang động, rừng nhiệt đới ẩm, rừng ngập mặn, rạn san hô và cỏ biển.',
    people:'Cộng đồng đảo gắn với nghề cá, dịch vụ cảng, du lịch và các hoạt động sinh kế phụ thuộc trực tiếp vào chất lượng môi trường biển.',
    role:'Bảo tồn đa dạng sinh học biển – đảo, đặc biệt voọc Cát Bà; nghiên cứu karst và phát triển du lịch sinh thái.',
    challenge:'Du lịch đông, hạ tầng ven biển, rác thải và áp lực lên sinh cảnh của các loài đặc hữu.',
    highlight:'Nơi sinh sống của voọc Cát Bà – loài linh trưởng đặc hữu cực kỳ nguy cấp.',
    source:'https://www.unesco.org/en/mab/cat-ba',
    image:{file:'Cat Ba.jpg', author:'Christophe95', license:'CC BY-SA 4.0'},
    video:{id:'1i5oo5KQdFE', title:'Voọc Cát Bà trước nguy cơ tuyệt chủng', channel:'VTV24'}
  },
  {
    id:'kien-giang', name:'Kiên Giang', unescoName:'Kien Giang',
    currentLocation:'An Giang', unescoLocation:'Kien Giang', region:'Miền Nam', environment:'Biển – đảo',
    type:['Biển – đảo','Rừng','Cỏ biển'], year:2006, area:'1.188.106 ha', lat:9.96, lng:104.53,
    summary:'Khu sinh quyển rất rộng gồm Phú Quốc, các vùng biển – đảo, rừng nhiệt đới, rừng tràm, rừng ngập mặn, cỏ biển và rạn san hô.',
    nature:'Sự kết hợp giữa đảo lớn, đảo nhỏ, rừng nhiệt đới, rừng tràm ngập nước, rừng ngập mặn, bãi triều, rạn san hô và thảm cỏ biển.',
    people:'Kinh tế địa phương gắn mạnh với nghề cá, nuôi trồng thủy sản, du lịch đảo và dịch vụ biển; Phú Quốc là không gian phát triển nổi bật.',
    role:'Bảo vệ nguồn lợi biển, sinh cảnh của bò biển và rùa biển; hỗ trợ nghề cá và phát triển kinh tế biển bền vững.',
    challenge:'Phát triển du lịch, khai thác thủy sản, ô nhiễm biển và suy giảm thảm cỏ biển – rạn san hô.',
    highlight:'Có các hệ sinh thái cỏ biển quan trọng đối với bò biển (dugong).',
    source:'https://www.unesco.org/en/mab/kien-giang',
    image:{file:'Phu Quoc, Viet Nam.jpg', author:'Trantuonglam', license:'CC BY-SA'},
    video:{id:'VlavGURdc58', title:'Có được tham quan trong Vườn Quốc gia Phú Quốc?', channel:'Truyền Hình Đồng Tháp'}
  },
  {
    id:'western-nghe-an', name:'Miền Tây Nghệ An', unescoName:'Western Nghe An',
    currentLocation:'Nghệ An', unescoLocation:'Nghe An', region:'Miền Trung', environment:'Núi – cao nguyên',
    type:['Rừng','Núi','Sông suối'], year:2007, area:'1.299.795 ha', lat:19.24, lng:104.82,
    summary:'Không gian rừng núi rộng lớn phía tây Nghệ An thuộc dãy Trường Sơn, có mức độ đa dạng sinh học rất cao.',
    nature:'Rừng nhiệt đới, núi cao, thung lũng, sông suối; Pù Mát là vùng lõi nổi bật với rừng nguyên sinh và hệ động thực vật phong phú.',
    people:'Không gian sinh sống của nhiều cộng đồng dân tộc, với văn hóa bản địa và sinh kế gắn với rừng, nông nghiệp và du lịch cộng đồng.',
    role:'Giữ rừng đầu nguồn, duy trì đa dạng sinh học Trường Sơn, bảo vệ nguồn nước và hỗ trợ sinh kế địa phương.',
    challenge:'Suy giảm rừng, săn bắt và khai thác tài nguyên; một bộ phận sinh kế còn phụ thuộc nhiều vào tài nguyên tự nhiên.',
    highlight:'Một trong những khu dự trữ sinh quyển có diện tích lớn nhất Việt Nam.',
    source:'https://www.unesco.org/en/mab/western-nghe',
    image:{file:'Vườn Quốc Gia Pù Mát② Con Cuông, Nghệ An.jpg', author:'KoheiU', license:'CC0'},
    video:{id:'HWhzCFWaMuM', title:'Khám phá Khu dự trữ sinh quyển miền Tây Nghệ An', channel:'Vietnam Tourism'}
  },
  {
    id:'mui-ca-mau', name:'Mũi Cà Mau', unescoName:'Mui Ca Mao',
    currentLocation:'Cà Mau', unescoLocation:'Ca Mau', region:'Miền Nam', environment:'Đất ngập nước',
    type:['Rừng ngập mặn','Đất ngập nước','Ven biển'], year:2009, area:'371.506 ha', lat:8.67, lng:104.82,
    summary:'Cảnh quan cực Nam đặc trưng với rừng ngập mặn, rừng tràm, bãi bồi và hệ sinh thái cửa sông – ven biển rất năng động.',
    nature:'Rừng đước, rừng tràm, bãi bồi, vùng triều và mạng lưới sông rạch; quá trình bồi tụ – xói lở diễn ra mạnh.',
    people:'Đời sống cư dân gắn với rừng – biển, nuôi trồng và đánh bắt thủy sản, dịch vụ du lịch Đất Mũi và văn hóa sông nước Nam Bộ.',
    role:'Chắn sóng, giữ đất, bảo vệ bờ biển; duy trì nguồn lợi thủy sản; lưu trữ carbon và tạo sinh kế từ rừng – biển.',
    challenge:'Sạt lở bờ biển, nước biển dâng, sụt lún và biến đổi dòng chảy.',
    highlight:'Cảnh quan “đất nở – rừng tiến ra biển” giúp học sinh quan sát trực tiếp quá trình bồi tụ ở cực Nam.',
    source:'https://www.unesco.org/en/mab/mui-ca-mao',
    image:{file:'Walkway railing along a mangrove river in Ca Mau.jpg', author:'Nevillenguyen310', license:'Wikimedia Commons'},
    video:{id:'U3dNbhSZ7u8', title:'Is Mui Ca Mau Sinking?', channel:'VTV4'}
  },
  {
    id:'cu-lao-cham', name:'Cù Lao Chàm – Hội An', unescoName:'Cu Lao Cham - Hoi An',
    currentLocation:'TP. Đà Nẵng', unescoLocation:'Quang Nam', region:'Miền Trung', environment:'Biển – đảo',
    type:['Biển – đảo','Rạn san hô','Rừng'], year:2009, area:'33.475 ha', lat:15.9496, lng:108.52,
    summary:'Khu sinh quyển kết nối quần đảo Cù Lao Chàm với không gian văn hóa – sinh thái Hội An và vùng cửa sông Thu Bồn.',
    nature:'Rạn san hô, rong biển, rừng trên đảo, bãi biển, vùng cửa sông và nhiều sinh cảnh biển – ven bờ phong phú.',
    people:'Cộng đồng đảo sống bằng nghề cá, dịch vụ du lịch và các mô hình bảo tồn dựa vào cộng đồng; Hội An tạo liên kết mạnh giữa thiên nhiên và văn hóa.',
    role:'Bảo tồn hệ sinh thái biển, duy trì nghề cá, phát triển du lịch xanh và kết nối bảo tồn thiên nhiên với di sản văn hóa.',
    challenge:'Rác thải nhựa, sức ép du lịch, neo đậu tàu thuyền, suy giảm san hô và tác động của bão.',
    highlight:'Mô hình nổi tiếng về giảm túi ni-lông và bảo tồn gắn với cộng đồng.',
    source:'https://www.unesco.org/en/mab/cu-lao-cham-hoi',
    image:{file:'Cu Lao Cham.JPG', author:'Lê Thy', license:'Public domain'},
    video:{id:'NxDmLNZ4GnY', title:'Cộng đồng chung tay bảo tồn biển Cù Lao Chàm', channel:'VTV4'}
  },
  {
    id:'dong-nai', name:'Đồng Nai', unescoName:'Dong Nai',
    currentLocation:'Đồng Nai', unescoLocation:'Dong Nai', region:'Miền Nam', environment:'Rừng',
    type:['Rừng','Đất ngập nước','Sông hồ'], year:2001, area:'756.000 ha', lat:11.48, lng:107.25,
    summary:'Không gian rừng nhiệt đới, sông hồ và đất ngập nước ở Đông Nam Bộ; phát triển từ Khu dự trữ sinh quyển Cát Tiên.',
    nature:'Rừng thường xanh lá rộng, rừng tre nứa, vùng ngập nước, sông suối và hồ tạo nên một hành lang sinh thái lớn ở Đông Nam Bộ.',
    people:'Khu vực có nhiều cộng đồng sinh sống quanh rừng; phát triển sinh kế bền vững cần gắn với giảm áp lực lên tài nguyên và động vật hoang dã.',
    role:'Bảo tồn rừng nhiệt đới và động vật hoang dã, bảo vệ nguồn nước, duy trì hành lang sinh thái và hỗ trợ du lịch tự nhiên.',
    challenge:'Chia cắt sinh cảnh, săn bắt trái phép, xung đột người – động vật và áp lực phát triển hạ tầng.',
    highlight:'UNESCO ghi mốc 2001; năm 2011 khu được mở rộng và mang tên Đồng Nai.',
    source:'https://www.unesco.org/en/mab/dong-nai',
    image:{file:'Cat Tien National Park.jpg', author:'Vyacheslav Argenberg', license:'CC BY 2.0'},
    video:{id:'--6RNepiuzs', title:'Khám phá Vườn quốc gia Cát Tiên', channel:'VTV24'}
  },
  {
    id:'langbiang', name:'Langbiang', unescoName:'Langbiang',
    currentLocation:'Lâm Đồng', unescoLocation:'Lam Dong', region:'Tây Nguyên', environment:'Núi – cao nguyên',
    type:['Núi','Rừng','Cao nguyên'], year:2015, area:'275.439 ha', lat:12.02, lng:108.46,
    summary:'Khu sinh quyển núi cao Nam Trường Sơn, gắn với Vườn quốc gia Bidoup – Núi Bà và không gian văn hóa Tây Nguyên.',
    nature:'Rừng núi cao, rừng thường xanh, rừng thông và các sinh cảnh cao nguyên tạo nên độ phân hóa rõ theo độ cao.',
    people:'Không gian văn hóa Tây Nguyên và sản xuất nông nghiệp cao nguyên đặt ra bài toán kết hợp bảo tồn rừng với sinh kế và du lịch.',
    role:'Bảo tồn hành lang đa dạng sinh học, bảo vệ rừng đầu nguồn, hỗ trợ nghiên cứu và phát triển nông nghiệp – du lịch bền vững.',
    challenge:'Mở rộng nông nghiệp, du lịch, cháy rừng và biến đổi khí hậu trên cao nguyên.',
    highlight:'Khu dự trữ sinh quyển thế giới đầu tiên ở Tây Nguyên.',
    source:'https://www.unesco.org/en/mab/langbiang',
    image:{file:'Lang Biang mountain 1.jpg', author:'Nomad Tales', license:'CC BY-SA 2.0'},
    video:{id:'qIcTjy82kX8', title:'Bảo tồn giá trị khu dự trữ sinh quyển Langbiang', channel:'VTC14'}
  },
  {
    id:'nui-chua', name:'Núi Chúa', unescoName:'Nui Chua',
    currentLocation:'Khánh Hòa', unescoLocation:'Ninh Thuan', region:'Miền Trung', environment:'Biển – đảo',
    type:['Rừng khô hạn','Biển','Rạn san hô'], year:2021, area:'106.646 ha', lat:11.69, lng:109.15,
    summary:'Một không gian hiếm có nơi hệ sinh thái khô hạn nhiệt đới gặp biển, rạn san hô, cỏ biển và bãi đẻ của rùa biển.',
    nature:'Rừng khô hạn, cây bụi chịu hạn, núi đá, bờ biển, rạn san hô và thảm cỏ biển nằm cạnh nhau trên một dải lãnh thổ hẹp.',
    people:'Cộng đồng ven biển và vùng bán khô hạn có sinh kế gắn với biển, nông nghiệp thích ứng khô hạn và dịch vụ du lịch sinh thái.',
    role:'Bảo tồn hệ sinh thái khô hạn độc đáo, rùa biển, san hô và đa dạng sinh học ven biển Nam Trung Bộ.',
    challenge:'Hạn hán, cháy rừng, sức ép du lịch ven biển, biến đổi khí hậu và tổn thương rạn san hô.',
    highlight:'Một trong những vùng khô hạn nhất Việt Nam nhưng có đa dạng sinh học rất đặc sắc.',
    source:'https://www.unesco.org/en/mab/nui-chua',
    image:{file:'Nui Chua National Park.jpg', author:'Suriya Vij', license:'Public domain'},
    video:{id:'BiiT5mIZlNY', title:'Khu dự trữ sinh quyển thế giới Núi Chúa – nơi giao hòa giữa rừng và biển', channel:'KTV Kết nối và Phát triển'}
  },
  {
    id:'kon-ha-nung', name:'Kon Hà Nừng', unescoName:'Kon Ha Nung Highland',
    currentLocation:'Gia Lai', unescoLocation:'Gia Lai', region:'Tây Nguyên', environment:'Núi – cao nguyên',
    type:['Rừng','Cao nguyên','Núi'], year:2021, area:'413.511 ha', lat:14.19, lng:108.4,
    summary:'Khu cao nguyên rừng rộng lớn ở trung tâm Tây Nguyên, với Kon Ka Kinh và Kon Chư Răng là những vùng lõi quan trọng.',
    nature:'Rừng nhiệt đới núi cao, thung lũng, sông suối và thác nước; đây là sinh cảnh của nhiều loài đặc hữu và quý hiếm.',
    people:'Các cộng đồng Tây Nguyên sinh sống quanh khu rừng với nông – lâm nghiệp, văn hóa bản địa và tiềm năng du lịch sinh thái.',
    role:'Bảo tồn đa dạng sinh học Tây Nguyên, duy trì nguồn nước và hỗ trợ lâm nghiệp – nông nghiệp bền vững.',
    challenge:'Mất và chia cắt rừng, săn bắt, khai thác tài nguyên và sức ép chuyển đổi mục đích sử dụng đất.',
    highlight:'Vùng lõi gồm Kon Ka Kinh và Kon Chư Răng – hai khu bảo tồn có giá trị sinh học cao.',
    source:'https://www.unesco.org/en/mab/kon-ha-nung-highland',
    image:{file:'K50 Waterfall Kon Chu Rang Nature Reserve Gia Lai Vietnam.png', author:'VinhNguyen.1257', license:'CC0'},
    video:{id:'6SGsQOPLVKM', title:'UNESCO công nhận 2 khu dự trữ sinh quyển thế giới tại Việt Nam', channel:'TOÀN CẢNH 24H'}
  },
  {
    id:'phong-nha', name:'Phong Nha – Kẻ Bàng', unescoName:'Phong Nha - Ke Bang',
    currentLocation:'Quảng Trị', unescoLocation:'Quang Binh', region:'Miền Trung', environment:'Karst – hang động',
    type:['Karst','Hang động','Rừng'], year:2026, area:'515.830 ha', lat:17.5175, lng:106.204,
    summary:'Không gian karst – hang động – rừng nhiệt đới đặc biệt ở miền Trung, được UNESCO ghi vào Mạng lưới Khu dự trữ sinh quyển thế giới năm 2026.',
    nature:'Khối karst đá vôi cổ, hệ thống hang động lớn, sông ngầm và rừng nhiệt đới tạo nên cảnh quan địa chất – sinh học rất đặc sắc.',
    people:'Du lịch hang động, dịch vụ và sinh kế vùng đệm phát triển mạnh; quản lí bền vững cần cân bằng bảo tồn với lợi ích cộng đồng.',
    role:'Bảo tồn địa chất – địa mạo và đa dạng sinh học, hỗ trợ nghiên cứu hang động, giáo dục môi trường và du lịch sinh thái có kiểm soát.',
    challenge:'Tác động du lịch, thời tiết cực đoan, quản lí vùng đệm rộng lớn và cân bằng bảo tồn với sinh kế địa phương.',
    highlight:'UNESCO ghi “Year of nomination: 2026” cho danh hiệu Khu dự trữ sinh quyển.',
    source:'https://www.unesco.org/en/mab/phong-nha-ke-bang',
    image:{file:'Phongnhakebang10.jpg', author:'Genghiskhanviet', license:'Public domain'},
    video:{id:'KTx1bnAQ-3M', title:'UNESCO vinh danh Phong Nha – Kẻ Bàng là Khu dự trữ sinh quyển thế giới', channel:'Truyền Hình Đồng Tháp'}
  }
];

const ISLAND_LABELS = [
  {name:'Quần đảo Hoàng Sa', lat:16.5, lng:112.0, major:true},
  {name:'Quần đảo Trường Sa', lat:9.8, lng:114.1, major:true},
  {name:'Cát Bà', lat:20.80, lng:107.00},
  {name:'Bạch Long Vĩ', lat:20.13, lng:107.72},
  {name:'Cồn Cỏ', lat:17.16, lng:107.34},
  {name:'Lý Sơn', lat:15.38, lng:109.12},
  {name:'Cù Lao Chàm', lat:15.95, lng:108.52},
  {name:'Phú Quý', lat:10.52, lng:108.94},
  {name:'Côn Đảo', lat:8.68, lng:106.60},
  {name:'Phú Quốc', lat:10.24, lng:103.96},
  {name:'Thổ Chu', lat:9.31, lng:103.48},
  {name:'Hòn Khoai', lat:8.43, lng:104.83}
];

// Đường bao đơn giản của phần đất liền Việt Nam để làm nổi bật lãnh thổ trên nền bản đồ.
// Các đảo và quần đảo được thể hiện riêng bằng lớp nhãn/điểm ở trên.
const VIETNAM_OUTLINE = {
  type:'Feature',
  properties:{name:'Việt Nam'},
  geometry:{type:'Polygon',coordinates:[[[
    108.05018,21.55238],[106.715068,20.696851],[105.881682,19.75205],[105.662006,19.058165],
    [106.426817,18.004121],[107.361954,16.697457],[108.269495,16.079742],[108.877107,15.276691],
    [109.33527,13.426028],[109.200136,11.666859],[108.36613,11.008321],[107.220929,10.364484],
    [106.405113,9.53084],[105.158264,8.59976],[104.795185,9.241038],[105.076202,9.918491],
    [104.334335,10.486544],[105.199915,10.88931],[106.24967,10.961812],[105.810524,11.567615],
    [107.491403,12.337206],[107.614548,13.535531],[107.382727,14.202441],[107.564525,15.202173],
    [107.312706,15.908538],[106.556008,16.604284],[105.925762,17.485315],[105.094598,18.666975],
    [103.896532,19.265181],[104.183388,19.624668],[104.822574,19.886642],[104.435,20.758733],
    [103.203861,20.766562],[102.754896,21.675137],[102.170436,22.464753],[102.706992,22.708795],
    [103.504515,22.703757],[104.476858,22.81915],[105.329209,23.352063],[105.811247,22.976892],
    [106.725403,22.794268],[106.567273,22.218205],[107.04342,21.811899],[108.05018,21.55238]
  ]]}
};
