(()=>{'use strict';
const CFG=window.APP_CONFIG||{},DATA=window.NV_DATA||{grades:{}};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const LEVELS=[['nb','Nhận biết'],['th','Thông hiểu'],['vd','Vận dụng']];
const TN_TYPES=[['single','Một lựa chọn đúng nhất'],['multiple','Nhiều lựa chọn đúng'],['truefalse','Đúng / Sai'],['short','Trả lời ngắn']];
const state={grade:'8',form:'mixed',provider:'gemini',apiOk:false,model:'',models:[],matrix:{read:{nb:[],th:[],vd:[]},write:{nb:[],th:[],vd:[]}},hiddenSpec:{read:{nb:new Set(),th:new Set(),vd:new Set()},write:{nb:new Set(),th:new Set(),vd:new Set()}},teacherSpec:{read:{nb:[],th:[],vd:[]},write:{nb:[],th:[],vd:[]}},dialog:null,exam:null,reviewTab:'matrix',proposal:null,history:[],aiReview:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=x=>Number(x||0),fmt=x=>{const v=n(x);return Number.isInteger(v)?String(v):String(Math.round(v*100)/100).replace('.',',')};
const clone=x=>JSON.parse(JSON.stringify(x));
const provider=()=>($('input[name="aiProvider"]:checked')?.value||'gemini');
const examForm=()=>($('input[name="examForm"]:checked')?.value||'mixed');
const writeSourceMode=()=>($('input[name="writeSourceMode"]:checked')?.value||'read');
const gradeData=()=>DATA.grades?.[state.grade]||{read:[],write:[]};
const readTrack=()=>gradeData().read.find(x=>x.id===$('#readTrack')?.value)||gradeData().read[0];
const writeTrack=()=>gradeData().write.find(x=>x.id===$('#writeTrack')?.value)||gradeData().write[0];
const apiBase=()=>String(CFG.API_BASE||'').replace(/\/$/,'');
async function post(path,body){if(!apiBase()||apiBase().includes('YOUR_SUBDOMAIN'))throw new Error('Chưa cấu hình API_BASE trong config.js.');const r=await fetch(apiBase()+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d;}
function aiParams(){const p=provider();return {provider:p,apiKey:p==='cloudflare'?'':($('#apiKey')?.value||'').trim(),model:$('#modelSelect')?.value||state.model};}
function showStep(name){$$('.panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${name}`));$$('.step-btn').forEach(x=>x.classList.toggle('active',x.dataset.step===name));if(name==='matrix')renderMatrix();if(name==='spec')renderSpec();if(name==='generate'){renderGenerateSummary();renderExam();}if(name==='review')renderReview();window.scrollTo({top:0,behavior:'smooth'});}
function resetDerived(){state.matrix={read:{nb:[],th:[],vd:[]},write:{nb:[],th:[],vd:[]}};state.hiddenSpec={read:{nb:new Set(),th:new Set(),vd:new Set()},write:{nb:new Set(),th:new Set(),vd:new Set()}};state.teacherSpec={read:{nb:[],th:[],vd:[]},write:{nb:[],th:[],vd:[]}};state.exam=null;state.history=[];state.proposal=null;state.aiReview=null;resetConfirm();}
function setApiStatus(msg,kind='neutral'){const el=$('#apiStatus');el.textContent=msg;el.className=`status-line ${kind==='neutral'?'':kind}`;$('#apiDot').className=`status-dot ${kind}`;}
function syncScores(){const a=n($('#readScore').value),b=n($('#writeScore').value),t=a+b;const el=$('#scoreSplitStatus');el.textContent=`Tổng: ${fmt(t)} điểm`;el.classList.toggle('bad',Math.abs(t-10)>.001);}
function renderScope(){const gd=gradeData();const rsel=$('#readTrack'),wsel=$('#writeTrack');const rcur=rsel.value,wcur=wsel.value;rsel.innerHTML=gd.read.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('');wsel.innerHTML=gd.write.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('');if(gd.read.some(x=>x.id===rcur))rsel.value=rcur;if(gd.write.some(x=>x.id===wcur))wsel.value=wcur;renderTrackDetails();}
function renderTrackDetails(){const r=readTrack(),w=writeTrack();$('#readTrackSource').textContent=`Nguồn đối chiếu: ${r?.source||'Chương trình 2018 + bộ đặc tả đúng lớp'}`;$('#writeTrackSource').textContent=`Nguồn đối chiếu: ${w?.source||'Chương trình 2018 + bộ đặc tả đúng lớp'}`;const selected=new Set($$('#viKnowledge input:checked').map(x=>x.value));$('#viKnowledge').innerHTML=(r?.vi||[]).map((x,i)=>`<label class="check-item"><input type="checkbox" value="${esc(x)}" ${selected.has(x)?'checked':''}/><span>${esc(x)}</span></label>`).join('')||'<div class="tiny">Không có tri thức tiếng Việt gợi ý trong dữ liệu hiện tại.</div>';}
function syncWriteSourceMode(){const m=writeSourceMode();$('#writeSeparatePanel').classList.toggle('hidden',m!=='separate');$('#writeRequirementPanel').classList.toggle('hidden',m!=='none');validateSources(false);}
function validateSources(show=true){const errs=[];if(!$('#readText').value.trim())errs.push('Chưa có ngữ liệu Đọc.');if(!$('#readSource').value.trim())errs.push('Chưa có nguồn ngữ liệu Đọc.');if(!$('#sourceConfirm').checked)errs.push('Chưa xác nhận ngữ liệu và nguồn.');const mode=writeSourceMode(),wt=writeTrack();if(mode==='separate'){if(!$('#writeText').value.trim())errs.push('Đã chọn ngữ liệu Viết riêng nhưng chưa nhập ngữ liệu.');if(!$('#writeSource').value.trim())errs.push('Ngữ liệu Viết riêng chưa có nguồn.');}if(mode==='none'){if(!$('#writeRequirement').value.trim())errs.push('Đã chọn không dùng ngữ liệu nhưng chưa nhập yêu cầu Viết cụ thể.');if(wt?.needsText)errs.push('Kiểu bài Viết đã chọn cần một tác phẩm/ngữ liệu cụ thể; hãy dùng ngữ liệu Đọc hoặc nhập ngữ liệu Viết riêng.');}const box=$('#sourceValidation');if(box){box.innerHTML=errs.length?`<div class="notice">⚠ ${errs.map(esc).join('<br>')}</div>`:'<div class="notice compact" style="border-left-color:#15803d;background:#f0fdf4;color:#166534">✓ Ngữ liệu đã đủ thông tin tối thiểu.</div>';}if(show&&errs.length)alert(errs.join('\n'));return !errs.length;}
function validateStep(target){if(target==='scope'){if(Math.abs(n($('#readScore').value)+n($('#writeScore').value)-10)>.001){alert('Tổng điểm Đọc + Viết phải bằng 10,0.');return false;}return true;}if(target==='sources'){return !!readTrack()&&!!writeTrack();}if(target==='matrix')return validateSources(true);if(target==='spec'){if(!validateMatrix(true))return false;}if(target==='generate'){if(!validateMatrix(true))return false;}if(target==='review'){if(!state.exam){alert('Hãy tạo đề trước.');return false;}}return true;}
function clearMatrixForForm(){state.form=examForm();if(state.form==='essay'){LEVELS.forEach(([lv])=>state.matrix.read[lv]=(state.matrix.read[lv]||[]).filter(x=>x.form==='TL'));}renderMatrix();resetConfirm();}
function rowsFor(cap,lv){return state.matrix[cap][lv]||[];}
function sumRows(rows){return rows.reduce((s,x)=>s+n(x.count)*n(x.points),0)}
function capPoints(cap){return LEVELS.reduce((s,[lv])=>s+sumRows(rowsFor(cap,lv)),0)}
function configText(rows,cap){if(!rows.length)return 'Chưa chọn';if(cap==='write')return rows.map(x=>`1* TL · ${fmt(x.points)}đ`).join('<br>');return rows.map(x=>`${x.count} ${x.form==='TNKQ'?'TNKQ':'TL'}${x.form==='TNKQ'?` · ${tnName(x.subtype)}`:''}<br>${fmt(n(x.count)*n(x.points))}đ`).join('<br>')}
function tnName(id){return Object.fromEntries(TN_TYPES)[id]||id}
function renderMatrix(){const mixed=examForm()==='mixed';let head=mixed?`<thead><tr><th rowspan="2">TT</th><th rowspan="2">Năng lực</th><th rowspan="2">Mạch nội dung</th><th colspan="2" class="nb-head">Nhận biết</th><th colspan="2" class="th-head">Thông hiểu</th><th colspan="2" class="vd-head">Vận dụng</th><th rowspan="2">Tổng điểm</th></tr><tr><th>TNKQ</th><th>TL</th><th>TNKQ</th><th>TL</th><th>TNKQ</th><th>TL</th></tr></thead>`:`<thead><tr><th>TT</th><th>Năng lực</th><th>Mạch nội dung</th><th class="nb-head">Nhận biết</th><th class="th-head">Thông hiểu</th><th class="vd-head">Vận dụng</th><th>Tổng điểm</th></tr></thead>`;const body=['read','write'].map((cap,i)=>{const trk=cap==='read'?readTrack():writeTrack();if(mixed){const cells=[];LEVELS.forEach(([lv])=>['TNKQ','TL'].forEach(f=>{if(cap==='write'&&f==='TNKQ'){cells.push('<td>—</td>');return;}const arr=rowsFor(cap,lv).filter(x=>x.form===f);cells.push(`<td><button class="matrix-cell-btn ${arr.length?'has-data':''}" data-cap="${cap}" data-level="${lv}" data-form="${f}">${configText(arr,cap)}</button></td>`)}));return `<tr><td>${i+1}</td><td><b>${cap==='read'?'Đọc':'Viết'}</b></td><td>${esc(trk?.label||'')}</td>${cells.join('')}<td><b>${fmt(capPoints(cap))}</b></td></tr>`}const cells=LEVELS.map(([lv])=>{const arr=rowsFor(cap,lv).filter(x=>x.form==='TL');return `<td><button class="matrix-cell-btn ${arr.length?'has-data':''}" data-cap="${cap}" data-level="${lv}" data-form="TL">${configText(arr,cap)}</button></td>`}).join('');return `<tr><td>${i+1}</td><td><b>${cap==='read'?'Đọc':'Viết'}</b></td><td>${esc(trk?.label||'')}</td>${cells}<td><b>${fmt(capPoints(cap))}</b></td></tr>`}).join('');$('#matrixTable').innerHTML=head+`<tbody>${body}</tbody>`;$$('.matrix-cell-btn').forEach(b=>b.addEventListener('click',()=>openMatrixDialog(b.dataset.cap,b.dataset.level,b.dataset.form)));const rp=capPoints('read'),wp=capPoints('write'),expectedR=n($('#readScore').value),expectedW=n($('#writeScore').value);$('#matrixSummary').innerHTML=`<span class="summary-chip">Đọc: ${fmt(rp)}/${fmt(expectedR)} điểm</span><span class="summary-chip">Viết: ${fmt(wp)}/${fmt(expectedW)} điểm</span><span class="summary-chip">Tổng: ${fmt(rp+wp)}/10 điểm</span>`;}
function openMatrixDialog(cap,level,form){const current=rowsFor(cap,level).filter(x=>x.form===form).map(clone);if(!current.length){if(cap==='write')current.push({form:'TL',count:1,points:0.5});else current.push(form==='TNKQ'?{form,count:1,points:0.5,subtype:'single'}:{form:'TL',count:1,points:1});}state.dialog={cap,level,form,rows:current};$('#addConfigBtn').classList.toggle('hidden',cap==='write');$('#dialogLevel').textContent=`${cap==='read'?'ĐỌC':'VIẾT'} · ${Object.fromEntries(LEVELS)[level]}`;$('#dialogTitle').textContent=form==='TNKQ'?'Thiết lập TNKQ':'Thiết lập tự luận';renderConfigRows();$('#matrixModalBackdrop').classList.remove('hidden');}
function renderConfigRows(){const d=state.dialog;if(!d)return;const root=$('#configRows');if(!d.rows.length){root.innerHTML='<div class="empty-state"><b>Đã xóa toàn bộ cấu hình của ô này.</b><br>Nhấn “Lưu cấu hình” để xóa khỏi ma trận, hoặc “+ Thêm cấu hình” để thiết lập lại.</div>';$('#dialogSummary').textContent='Tổng ô: 0 điểm';return;}root.innerHTML=d.rows.map((r,i)=>{if(d.cap==='write')return `<div class="config-row write-config"><label>Điểm phân bổ cho mức<input data-i="${i}" data-k="points" type="number" min="0.25" step="0.25" value="${r.points}"></label><button class="mini-btn remove-config" data-i="${i}">✕ Xóa</button></div>`;return `<div class="config-row">${d.form==='TNKQ'?`<label>Kiểu<select data-i="${i}" data-k="subtype">${TN_TYPES.map(([v,l])=>`<option value="${v}" ${r.subtype===v?'selected':''}>${l}</option>`).join('')}</select></label>`:'<div></div>'}<label>Số câu<input data-i="${i}" data-k="count" type="number" min="1" step="1" value="${r.count}"></label><label>Điểm/câu<input data-i="${i}" data-k="points" type="number" min="0.25" step="0.25" value="${r.points}"></label><button class="mini-btn remove-config" data-i="${i}">✕</button></div>`}).join('');$$('[data-k]',root).forEach(x=>x.addEventListener('change',()=>{const i=+x.dataset.i,k=x.dataset.k;d.rows[i][k]=k==='subtype'?x.value:Number(x.value);renderDialogSummary()}));$$('.remove-config',root).forEach(b=>b.addEventListener('click',()=>{d.rows.splice(+b.dataset.i,1);renderConfigRows()}));renderDialogSummary();}
function renderDialogSummary(){const d=state.dialog;if(!d)return;$('#dialogSummary').textContent=`Tổng ô: ${fmt(d.cap==='write'?d.rows.reduce((s,x)=>s+n(x.points),0):sumRows(d.rows))} điểm`;}
function saveDialog(){const d=state.dialog;if(!d)return;let all=state.matrix[d.cap][d.level].filter(x=>x.form!==d.form);const clean=d.rows.filter(x=>n(x.points)>0&&n(x.count||1)>0).map(x=>({...x,form:d.form,count:d.cap==='write'?1:Math.max(1,Math.round(n(x.count)))}));state.matrix[d.cap][d.level]=all.concat(clean);closeDialog();renderMatrix();resetConfirm();}
function closeDialog(){$('#matrixModalBackdrop').classList.add('hidden');$('#addConfigBtn').classList.remove('hidden');state.dialog=null;}
function validateMatrix(show=true){const rp=capPoints('read'),wp=capPoints('write'),er=n($('#readScore').value),ew=n($('#writeScore').value),errs=[];if(Math.abs(er+ew-10)>.001)errs.push('Điểm Đọc + Viết chưa bằng 10.');if(Math.abs(rp-er)>.001)errs.push(`Ma trận Đọc đang ${fmt(rp)} điểm, cần ${fmt(er)} điểm.`);if(Math.abs(wp-ew)>.001)errs.push(`Ma trận Viết đang ${fmt(wp)} điểm, cần ${fmt(ew)} điểm.`);if(state.form==='essay'&&LEVELS.some(([lv])=>rowsFor('read',lv).some(x=>x.form==='TNKQ')))errs.push('Đề 100% tự luận không được có TNKQ.');if(show&&errs.length)alert(errs.join('\n'));return !errs.length;}
function specList(cap,lv){const trk=cap==='read'?readTrack():writeTrack();return trk?.[lv]||[]}
function visibleSpec(cap,lv){return [...specList(cap,lv).filter((x,i)=>!state.hiddenSpec[cap][lv].has(i)),...state.teacherSpec[cap][lv]]}
function renderSpec(){const sections=['read','write'].map(cap=>{const trk=cap==='read'?readTrack():writeTrack();const levels=LEVELS.map(([lv,label])=>{const source=specList(cap,lv);const bullets=source.map((x,i)=>`<div class="spec-bullet ${state.hiddenSpec[cap][lv].has(i)?'hidden-source':''}"><span class="bullet-text">– ${esc(x)}</span><button class="mini-btn" data-spec-toggle="${cap}|${lv}|${i}">${state.hiddenSpec[cap][lv].has(i)?'Khôi phục':'Ẩn'}</button></div>`).join('')||'<div class="tiny">Nguồn hiện không có đặc tả ở mức này.</div>';const teacher=state.teacherSpec[cap][lv].map((x,i)=>`<div class="spec-bullet"><span class="bullet-text">– ${esc(x)}</span><button class="mini-btn" data-teacher-remove="${cap}|${lv}|${i}">Xóa</button></div>`).join('');return `<div class="spec-level"><h4>${label}</h4>${bullets}<div class="teacher-added"><b>Đặc tả bổ sung của giáo viên</b>${teacher||'<div class="tiny">Chưa bổ sung.</div>'}<div class="teacher-row"><input data-teacher-input="${cap}|${lv}" placeholder="Nhập một đặc tả bổ sung có căn cứ..."><button class="mini-btn" data-teacher-add="${cap}|${lv}">+ Thêm</button></div></div></div>`}).join('');return `<section class="spec-section"><div class="spec-section-head"><div><b>Năng lực ${cap==='read'?'Đọc':'Viết'}</b><div class="tiny">${esc(trk?.label||'')}</div></div><button class="mini-btn" data-restore-spec="${cap}">Khôi phục đặc tả nguồn</button></div><div class="spec-section-body">${levels}</div></section>`}).join('');$('#specEditor').innerHTML=sections;$$('[data-spec-toggle]').forEach(b=>b.addEventListener('click',()=>{const [c,l,i]=b.dataset.specToggle.split('|');const set=state.hiddenSpec[c][l];set.has(+i)?set.delete(+i):set.add(+i);renderSpec();resetConfirm()}));$$('[data-restore-spec]').forEach(b=>b.addEventListener('click',()=>{LEVELS.forEach(([lv])=>state.hiddenSpec[b.dataset.restoreSpec][lv].clear());renderSpec();resetConfirm()}));$$('[data-teacher-add]').forEach(b=>b.addEventListener('click',()=>{const [c,l]=b.dataset.teacherAdd.split('|'),inp=$(`[data-teacher-input="${c}|${l}"]`),v=inp.value.trim();if(v){state.teacherSpec[c][l].push(v);renderSpec();resetConfirm()}}));$$('[data-teacher-remove]').forEach(b=>b.addEventListener('click',()=>{const [c,l,i]=b.dataset.teacherRemove.split('|');state.teacherSpec[c][l].splice(+i,1);renderSpec();resetConfirm()}));}
function sourcePayload(){const wm=writeSourceMode();return {read:{title:$('#readTitle').value.trim(),author:$('#readAuthor').value.trim(),source:$('#readSource').value.trim(),text:$('#readText').value},write:{mode:wm,title:wm==='separate'?$('#writeTitle').value.trim():'',author:wm==='separate'?$('#writeAuthor').value.trim():'',source:wm==='separate'?$('#writeSource').value.trim():'',text:wm==='separate'?$('#writeText').value:'',requirement:wm==='none'?$('#writeRequirement').value.trim():'',note:$('#writeNote').value.trim()}}}
function matrixPayload(){const out=[];['read','write'].forEach(cap=>LEVELS.forEach(([lv,label])=>rowsFor(cap,lv).forEach((r,i)=>out.push({id:`${cap}_${lv}_${i}_${r.form}`,ability:cap==='read'?'Đọc':'Viết',level:lv,levelName:label,form:r.form,subtype:r.subtype||'essay',count:n(r.count||1),pointsPerQuestion:n(r.points),total:n(r.count||1)*n(r.points)}))));return out}
function buildPayload(){const vi=$$('#viKnowledge input:checked').map(x=>x.value),extra=$('#viExtra').value.trim();if(extra)vi.push(extra);return {setup:{agency:$('#agency').value.trim(),schoolLine1:$('#schoolLine1').value.trim(),schoolLine2:$('#schoolLine2').value.trim(),schoolYear:$('#schoolYear').value.trim(),examType:$('#examType').value,grade:state.grade,duration:n($('#duration').value),examCodes:n($('#examCodes').value),examForm:examForm(),readScore:n($('#readScore').value),writeScore:n($('#writeScore').value)},scope:{read:{id:readTrack()?.id,label:readTrack()?.label,viKnowledge:vi},write:{id:writeTrack()?.id,label:writeTrack()?.label,needsText:!!writeTrack()?.needsText}},materials:sourcePayload(),matrix:matrixPayload(),descriptors:{read:Object.fromEntries(LEVELS.map(([lv])=>[lv,visibleSpec('read',lv)])),write:Object.fromEntries(LEVELS.map(([lv])=>[lv,visibleSpec('write',lv)]))}}}
function renderGenerateSummary(){$('#generateSummary').textContent=`Lớp ${state.grade} · ${examForm()==='mixed'?'TNKQ + tự luận':'100% tự luận'} · Đọc ${fmt($('#readScore').value)}đ · Viết ${fmt($('#writeScore').value)}đ · ${n($('#examCodes').value)} mã đề.`;}
function distributeSingleAnswers(exam){(exam?.examCodes||[]).forEach(code=>{const qs=(code.readQuestions||[]).filter(q=>q.form==='TNKQ'&&q.subtype==='single'&&Array.isArray(q.options)&&q.options.length===4);qs.forEach((q,i)=>{const target=['A','B','C','D'][i%4],cur=String(q.answer||'A').toUpperCase();const ci=cur.charCodeAt(0)-65,ti=target.charCodeAt(0)-65;if(ci>=0&&ci<4&&ti>=0&&ti<4&&ci!==ti){[q.options[ci],q.options[ti]]=[q.options[ti],q.options[ci]];if(q.distractor===cur)q.distractor=target;else if(q.distractor===target)q.distractor=cur;q.answer=target;}})});return exam}
async function generateExam(){if(!state.apiOk)return alert('Hãy kiểm tra API/nhà cung cấp AI trước.');if(!validateSources(true)||!validateMatrix(true))return;const btn=$('#generateBtn');btn.disabled=true;$('#generateStatus').textContent='Đang tạo đề và kiểm tra tính nhất quán...';try{const data=await post('/api/generate',{...aiParams(),payload:buildPayload()});state.exam=distributeSingleAnswers(data);state.history=[];state.proposal=null;state.aiReview=null;renderExam();renderReview();resetConfirm();$('#generateStatus').textContent='✓ Đã tạo đề. Hãy kiểm tra kĩ trước khi xuất Word.';}catch(e){$('#generateStatus').textContent='✕ '+e.message;}finally{btn.disabled=false;}}
function qHtml(q){let h=`<div class="preview-q"><b>Câu ${esc(q.number)} (${fmt(q.points)} điểm):</b> ${esc(q.prompt||'')}`;if(q.form==='TNKQ'&&Array.isArray(q.options))h+=`<div class="preview-options">${q.options.map((x,i)=>`<div>${String.fromCharCode(65+i)}. ${esc(String(x).replace(/^\s*[A-D][.)]\s*/i,''))}</div>`).join('')}</div>`;if(q.subtype==='truefalse'&&Array.isArray(q.statements))h+=`<div>${q.statements.map((x,i)=>`<div>${String.fromCharCode(97+i)}) ${esc(x.text||x)}</div>`).join('')}</div>`;return h+'</div>'}
function materialHtml(mat){const title=mat.title?`<div class="bold" style="text-align:center">${esc(mat.title)}</div>`:'';const auth=mat.author?`<div class="tiny" style="text-align:center">${esc(mat.author)}</div>`:'';return `${title}${auth}<div class="material-preview">${esc(mat.text)}</div><div class="material-source">${esc(mat.source)}</div>`}
function renderExam(){const root=$('#examPreview');if(!state.exam?.examCodes?.length){root.innerHTML='';return}const mat=sourcePayload().read;root.innerHTML=state.exam.examCodes.map(code=>`<div class="preview-code"><h3>ĐỀ ${esc(code.code||'A')}</h3><div class="part-heading">PHẦN I. ĐỌC (${fmt($('#readScore').value)} điểm)</div><p><b>Đọc văn bản và thực hiện yêu cầu:</b></p>${materialHtml(mat)}${(code.readQuestions||[]).map(qHtml).join('')}<div class="part-heading">PHẦN II. VIẾT (${fmt($('#writeScore').value)} điểm)</div><div class="preview-q"><b>${esc(code.write?.prompt||'Chưa có yêu cầu Viết.')}</b></div></div>`).join('');}
function answerText(q){if(Array.isArray(q.answer))return q.answer.join(', ');if(q.answer&&typeof q.answer==='object')return Object.entries(q.answer).map(([k,v])=>`${k}: ${v===true?'Đ':v===false?'S':v}`).join('; ');return String(q.answer??'')}
function markingHtml(){
  if(!state.exam?.examCodes?.length)return '<div class="empty-state">Chưa có đề.</div>';
  const codes=state.exam.examCodes;
  let html='<h3>PHẦN I. ĐỌC</h3>';
  const tn0=(codes[0].readQuestions||[]).filter(q=>q.form==='TNKQ');
  if(tn0.length){
    const groups=new Map();tn0.forEach(q=>groups.set(`${q.subtype}|${q.points}`,{subtype:q.subtype,points:q.points}));
    groups.forEach(g=>{html+=`<div class="marking-rubric">${esc(tnName(g.subtype))}: Mỗi câu đúng được ${fmt(g.points)} điểm.</div>`});
    html+='<div class="table-scroll"><table class="review-marking-table"><thead><tr><th>Câu</th>'+tn0.map(q=>`<th>${esc(q.number)}</th>`).join('')+'</tr></thead><tbody>';
    codes.forEach(c=>{const qs=(c.readQuestions||[]).filter(q=>q.form==='TNKQ');html+=`<tr><th>Đề ${esc(c.code)}</th>${qs.map(q=>`<td>${esc(answerText(q))}</td>`).join('')}</tr>`});
    html+='</tbody></table></div>';
  }
  const tlCodes=codes.map(c=>(c.readQuestions||[]).filter(q=>q.form==='TL'));
  const max=Math.max(...tlCodes.map(a=>a.length),0);
  if(max){
    html+='<h4>II. TỰ LUẬN</h4><div class="table-scroll"><table class="review-marking-table"><thead><tr><th>Câu</th>'+codes.map(c=>`<th>ĐỀ ${esc(c.code)}</th>`).join('')+'<th>Điểm</th></tr></thead><tbody>';
    for(let i=0;i<max;i++){
      const qs=tlCodes.map(a=>a[i]);let cells='';qs.forEach(q=>{if(!q){cells+='<td></td>';return;}let inside=`<div>${esc(answerText(q))}</div>`;if(q.rubric?.length){inside+='<div class="marking-label">Hướng dẫn chấm:</div>'+q.rubric.map(r=>`<div class="marking-rubric">– ${esc(r.content)} (${fmt(r.points)}đ)</div>`).join('')}cells+=`<td>${inside}</td>`});
      html+=`<tr><td>${esc(qs.find(Boolean)?.number||'')}</td>${cells}<td>${fmt(qs.find(Boolean)?.points||0)}</td></tr>`;
    }
    html+='</tbody></table></div>';
  }
  html+='<h3>PHẦN II. VIẾT</h3>';
  codes.forEach(c=>{
    let inner=`<p><b>Yêu cầu:</b> ${esc(c.write?.prompt||'')}</p><p class="tiny">HS có thể trình bày, diễn đạt theo cách riêng, miễn là hợp lí hoặc tương tự “Yêu cầu cần đạt”.</p>`;
    (c.write?.rubric||[]).forEach(g=>{inner+=`<div><b>${esc(g.group||'Tiêu chí')}</b>${g.points!=null?` (${fmt(g.points)}đ)`:''}`;if(g.content)inner+=`<div>${esc(g.content)}</div>`;(g.details||[]).forEach(d=>{inner+=`<div class="marking-rubric">– ${esc(d.content||d)}${d.points!=null?` (${fmt(d.points)}đ)`:''}</div>`});inner+='</div>'});
    if(c.write?.bands?.length){inner+='<div class="marking-label">Biểu điểm</div>';c.write.bands.forEach(b=>inner+=`<div>– ${esc(b.label)}: ${esc(b.description)}</div>`)}
    html+=`<div class="spec-section"><div class="spec-section-head"><b>Đề ${esc(c.code)}</b></div><div class="spec-section-body">${inner}</div></div>`;
  });
  return html;
}
function matrixHtml(){return $('#matrixTable').outerHTML+`<div class="matrix-summary">${$('#matrixSummary').innerHTML}</div>`}
function specHtml(){return $('#specEditor').innerHTML||'<div class="empty-state">Mở bước Bản đặc tả để xem.</div>'}
function renderReview(){if(!$('#reviewPreview'))return;$$('.review-tab').forEach(b=>b.classList.toggle('active',b.dataset.reviewTab===state.reviewTab));const titles={matrix:'Ma trận',spec:'Bản đặc tả',exam:'Đề kiểm tra',marking:'Hướng dẫn chấm'};$('#reviewPreviewTitle').textContent=titles[state.reviewTab];if(state.reviewTab==='matrix'){$('#reviewPreview').innerHTML=matrixHtml()}else if(state.reviewTab==='spec'){$('#reviewPreview').innerHTML=specHtml()}else if(state.reviewTab==='exam'){$('#reviewPreview').innerHTML=$('#examPreview').innerHTML||'<div class="empty-state">Chưa tạo đề.</div>'}else $('#reviewPreview').innerHTML=markingHtml();renderAiScopes();renderSafety();updateExportGate();}
function renderAiScopes(){const s=$('#aiScope'),cur=s.value;let h='<option value="">Chọn phạm vi...</option>';for(let ci=0;ci<(state.exam?.examCodes?.length||0);ci++){const c=state.exam.examCodes[ci];h+=`<optgroup label="Đề ${esc(c.code)}">`;for(let qi=0;qi<(c.readQuestions||[]).length;qi++){const q=c.readQuestions[qi];h+=`<option value="read|${ci}|${qi}">Câu ${q.number} – Đọc</option><option value="marking|${ci}|${qi}">HDC câu ${q.number}</option>`}h+=`<option value="write|${ci}|0">Phần Viết</option><option value="writeMarking|${ci}|0">HDC phần Viết</option></optgroup>`}s.innerHTML=h;if([...s.options].some(o=>o.value===cur))s.value=cur;}
function localSafety(){const out=[];if(!state.exam)return out;const obscene=/\b(địt|đụ|đéo|lồn|cặc|buồi|fuck|shit)\b/iu;const dangerous=/(?:cách|hướng dẫn|các bước).{0,50}(?:chế tạo|làm).{0,30}(?:bom|chất nổ|vũ khí)|(?:cách|hướng dẫn).{0,50}(?:hack|trộm|gian lận)/iu;(state.exam.examCodes||[]).forEach(c=>{(c.readQuestions||[]).forEach(q=>{const t=[q.prompt,...(q.options||[]),answerText(q),...(q.rubric||[]).map(r=>r.content)].join(' ');if(obscene.test(t))out.push({severity:'block',category:'Ngôn ngữ',code:c.code,questionNumber:q.number,message:'Có dấu hiệu từ ngữ tục tĩu/phản cảm.'});if(dangerous.test(t))out.push({severity:'block',category:'An toàn/pháp luật',code:c.code,questionNumber:q.number,message:'Có dấu hiệu hướng dẫn hành vi nguy hiểm/vi phạm.'})})});return out}
function renderSafety(){const root=$('#safetyReport'),items=[...localSafety(),...(state.aiReview?.issues||[])];root.classList.remove('hidden');root.innerHTML=items.length?`<b>Rà soát (${items.length})</b>${items.map(x=>`<div class="safety-issue"><span class="safety-badge ${x.severity||'warning'}">${x.severity==='block'?'CẦN SỬA':x.severity==='info'?'THÔNG TIN':'KIỂM TRA'}</span><div><b>${esc(x.category||'')}</b>${x.code?` · Đề ${esc(x.code)}`:''}${x.questionNumber?` · Câu ${esc(x.questionNumber)}`:''}<div>${esc(x.message||'')}</div>${x.suggestion?`<div class="tiny">Gợi ý: ${esc(x.suggestion)}</div>`:''}</div></div>`).join('')}`:'<b>Rà soát an toàn</b><div class="tiny">Chưa phát hiện cảnh báo tự động. AI vẫn có thể sai; giáo viên cần kiểm tra thủ công.</div>';}
function resetConfirm(){if($('#reviewConfirm'))$('#reviewConfirm').checked=false;updateExportGate()}
function updateExportGate(){if($('#exportDocxBtn'))$('#exportDocxBtn').disabled=!state.exam||!$('#reviewConfirm')?.checked||localSafety().some(x=>x.severity==='block')}
function appendChat(kind,text){const log=$('#aiChatLog');const d=document.createElement('div');d.className=kind==='user'?'chat-user':'chat-ai';d.textContent=text;log.appendChild(d);log.scrollTop=log.scrollHeight}
async function aiEdit(){if(!state.apiOk)return alert('Hãy kiểm tra AI trước.');const scope=$('#aiScope').value,req=$('#aiEditRequest').value.trim();if(!scope||!req)return alert('Hãy chọn phạm vi và nhập yêu cầu.');const [kind,ci,qi]=scope.split('|');const c=state.exam.examCodes[+ci];let target=kind.startsWith('write')?c.write:c.readQuestions[+qi];appendChat('user',req);$('#aiEditBtn').disabled=true;try{const data=await post('/api/refine',{...aiParams(),payload:buildPayload(),target:{kind,codeIndex:+ci,questionIndex:+qi,code:c.code,item:clone(target)},teacherRequest:req});state.proposal={...data,scope:{kind,ci:+ci,qi:+qi}};renderProposal();appendChat('ai',data.summary||'AI đã tạo đề xuất.');}catch(e){appendChat('ai','Lỗi: '+e.message)}finally{$('#aiEditBtn').disabled=false}}
function proposalText(p){if(!p)return '';if(p.kind==='write'||p.rubric)return JSON.stringify(p,null,2);return JSON.stringify(p,null,2)}
function renderProposal(){const b=$('#aiProposal');if(!state.proposal?.proposal){b.classList.add('hidden');b.innerHTML='';return}b.classList.remove('hidden');b.innerHTML=`<b>Đề xuất của AI</b><div class="tiny">${esc(state.proposal.summary||'')}</div><div class="proposal-preview">${esc(proposalText(state.proposal.proposal))}</div><div class="proposal-actions"><button class="btn primary" id="applyProposal">Áp dụng</button><button class="btn ghost" id="discardProposal">Bỏ qua</button></div>`;$('#applyProposal').onclick=applyProposal;$('#discardProposal').onclick=()=>{state.proposal=null;renderProposal()};}
function applyProposal(){const p=state.proposal;if(!p)return;state.history.push(clone(state.exam));if(state.history.length>10)state.history.shift();const {kind,ci,qi}=p.scope;if(kind==='read'||kind==='marking')state.exam.examCodes[ci].readQuestions[qi]=clone(p.proposal);else state.exam.examCodes[ci].write=clone(p.proposal);state.exam=distributeSingleAnswers(state.exam);state.proposal=null;state.aiReview=null;renderProposal();renderExam();renderReview();resetConfirm();$('#undoEditBtn').disabled=false;appendChat('ai','Đã áp dụng. Hãy kiểm tra lại nội dung và điểm.');}
function undoEdit(){if(!state.history.length)return;state.exam=state.history.pop();state.proposal=null;state.aiReview=null;renderExam();renderReview();resetConfirm();$('#undoEditBtn').disabled=!state.history.length;appendChat('ai','Đã hoàn tác lần chỉnh gần nhất.');}
async function aiReview(){if(!state.apiOk)return alert('Hãy kiểm tra AI trước.');if(!state.exam)return alert('Chưa có đề.');const b=$('#aiReviewBtn');b.disabled=true;b.textContent='Đang rà soát…';try{state.aiReview=await post('/api/review',{...aiParams(),payload:buildPayload(),exam:state.exam});renderSafety();appendChat('ai',state.aiReview.summary||'Đã rà soát toàn bộ đề.')}catch(e){appendChat('ai','Rà soát lỗi: '+e.message)}finally{b.disabled=false;b.textContent='🔍 AI rà soát toàn bộ'}}
function syncProvider(){state.provider=provider();state.apiOk=false;const p=state.provider;$('#personalApiPanel').classList.toggle('hidden',p==='cloudflare');$('#geminiGuide').href=CFG.GEMINI_GUIDE_URL||'#';const urls={gemini:'https://aistudio.google.com/apikey',openai:'https://platform.openai.com/api-keys',xai:'https://console.x.ai/',cloudflare:'https://dash.cloudflare.com/'};$('#providerConsole').href=urls[p];$('#geminiGuide').style.display=p==='gemini'?'inline':'none';$('#modelSelect').innerHTML='<option>Chưa kiểm tra...</option>';$('#modelSelect').disabled=true;setApiStatus(`Chưa kiểm tra ${p==='gemini'?'Gemini':p==='openai'?'OpenAI':p==='xai'?'xAI Grok':'Cloudflare Workers AI'}.`,'neutral');}
async function testApi(){const p=provider(),key=$('#apiKey').value.trim();if(p!=='cloudflare'&&!key)return setApiStatus('Vui lòng nhập API key.','bad');const b=$('#testApiBtn');b.disabled=true;b.textContent='Đang kiểm tra…';try{const d=await post('/api/test-provider',{provider:p,apiKey:key});state.models=d.models||[];state.model=d.recommended||state.models[0]||'';$('#modelSelect').disabled=!state.models.length;$('#modelSelect').innerHTML=state.models.map(m=>`<option value="${esc(m)}" ${m===state.model?'selected':''}>${esc(d.modelLabels?.[m]||m)}</option>`).join('');state.apiOk=true;setApiStatus('✓ '+(d.message||'API hoạt động.'),'ok')}catch(e){state.apiOk=false;setApiStatus('✕ '+e.message,'bad')}finally{b.disabled=false;b.textContent='Kiểm tra API'}}
// DOCX
const xEsc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
function wr(text,{b=false,i=false,sz=22}={}){return `<w:r><w:rPr>${b?'<w:b/>':''}${i?'<w:i/>':''}<w:sz w:val="${sz}"/><w:szCs w:val="${sz}"/><w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:cs="Times New Roman"/></w:rPr><w:t xml:space="preserve">${xEsc(text)}</w:t></w:r>`}
function wp(text='',o={}){const jc=o.align?`<w:jc w:val="${o.align}"/>`:'';return `<w:p><w:pPr>${jc}<w:spacing w:after="${o.after??60}" w:line="240" w:lineRule="auto"/></w:pPr>${wr(text,o)}</w:p>`}
function wpRuns(runs=[],o={}){const jc=o.align?`<w:jc w:val="${o.align}"/>`:'';return `<w:p><w:pPr>${jc}<w:spacing w:after="${o.after??60}" w:line="240" w:lineRule="auto"/></w:pPr>${runs.map(r=>wr(r.text,r)).join('')}</w:p>`}
function tc(content,{span=1,vMerge=null,fill=null,width=null}={}){return `<w:tc><w:tcPr>${span>1?`<w:gridSpan w:val="${span}"/>`:''}${vMerge==='restart'?'<w:vMerge w:val="restart"/>':vMerge==='continue'?'<w:vMerge/>':''}${fill?`<w:shd w:fill="${fill}"/>`:''}${width?`<w:tcW w:w="${width}" w:type="dxa"/>`:''}<w:vAlign w:val="center"/></w:tcPr>${content||wp('')}</w:tc>`}
function tr(cells){return `<w:tr>${cells.join('')}</w:tr>`}
function tbl(rows,widths=[]){return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="single" w:sz="6"/><w:left w:val="single" w:sz="6"/><w:bottom w:val="single" w:sz="6"/><w:right w:val="single" w:sz="6"/><w:insideH w:val="single" w:sz="4"/><w:insideV w:val="single" w:sz="4"/></w:tblBorders></w:tblPr>${widths.length?`<w:tblGrid>${widths.map(w=>`<w:gridCol w:w="${w}"/>`).join('')}</w:tblGrid>`:''}${rows.join('')}</w:tbl>`}
function headerDoc(title){return wpRuns([{text:$('#agency').value,b:true},{text:'\t'+$('#examType').value,b:true}],{align:'center'})+wpRuns([{text:$('#schoolLine1').value,b:true},{text:'\tNĂM HỌC '+$('#schoolYear').value,b:true}],{align:'center'})+wpRuns([{text:$('#schoolLine2').value,b:true}],{align:'left'})+wp(`MÔN: NGỮ VĂN – Lớp ${state.grade}`,{b:true,align:'center',sz:24})+wp(`Thời gian làm bài: ${$('#duration').value} phút (không kể thời gian phát đề)`,{align:'center'});}
function matrixDoc(){const mixed=examForm()==='mixed',rows=[];if(mixed){rows.push(tr([tc(wp('TT',{b:true,align:'center'}),{vMerge:'restart',fill:'EDEBFA'}),tc(wp('Năng lực',{b:true,align:'center'}),{vMerge:'restart',fill:'EDEBFA'}),tc(wp('Mạch nội dung',{b:true,align:'center'}),{vMerge:'restart',fill:'EDEBFA'}),tc(wp('Nhận biết',{b:true,align:'center'}),{span:2,fill:'DBEAFE'}),tc(wp('Thông hiểu',{b:true,align:'center'}),{span:2,fill:'D1FAE5'}),tc(wp('Vận dụng',{b:true,align:'center'}),{span:2,fill:'FFEDD5'}),tc(wp('Tổng điểm',{b:true,align:'center'}),{vMerge:'restart',fill:'EDEBFA'})]));rows.push(tr([tc('',{vMerge:'continue'}),tc('',{vMerge:'continue'}),tc('',{vMerge:'continue'}),...['TNKQ','TL','TNKQ','TL','TNKQ','TL'].map(x=>tc(wp(x,{b:true,align:'center'}),{fill:'F5F7FB'})),tc('',{vMerge:'continue'})]));}else rows.push(tr(['TT','Năng lực','Mạch nội dung','Nhận biết','Thông hiểu','Vận dụng','Tổng điểm'].map(x=>tc(wp(x,{b:true,align:'center'}),{fill:'EDEBFA'}))));['read','write'].forEach((cap,idx)=>{const trk=cap==='read'?readTrack():writeTrack();const cells=[tc(wp(String(idx+1),{align:'center'})),tc(wp(cap==='read'?'Đọc':'Viết',{b:true,align:'center'})),tc(wp(trk?.label||''))];if(mixed){LEVELS.forEach(([lv])=>['TNKQ','TL'].forEach(f=>{if(cap==='write'&&f==='TNKQ')cells.push(tc(wp('—',{align:'center'})));else cells.push(tc(wp(configText(rowsFor(cap,lv).filter(x=>x.form===f),cap).replace(/<br>/g,'; ').replace(/<[^>]+>/g,''),{align:'center'})))}))}else LEVELS.forEach(([lv])=>cells.push(tc(wp(configText(rowsFor(cap,lv).filter(x=>x.form==='TL'),cap).replace(/<br>/g,'; ').replace(/<[^>]+>/g,''),{align:'center'}))));cells.push(tc(wp(fmt(capPoints(cap)),{b:true,align:'center'})));rows.push(tr(cells));});return tbl(rows)}
function specDoc(){const rows=[tr(['TT','Năng lực','Mạch nội dung','Mức độ đánh giá','Nhận biết','Thông hiểu','Vận dụng'].map(x=>tc(wp(x,{b:true,align:'center'}),{fill:'EDEBFA'})))];['read','write'].forEach((cap,idx)=>{const trk=cap==='read'?readTrack():writeTrack();let desc='';LEVELS.forEach(([lv,label])=>{desc+=wp(label+':',{b:true});visibleSpec(cap,lv).forEach(x=>desc+=wp('– '+x));});rows.push(tr([tc(wp(String(idx+1),{align:'center'})),tc(wp(cap==='read'?'Đọc':'Viết',{b:true})),tc(wp(trk?.label||'')),tc(desc),...LEVELS.map(([lv])=>tc(wp(configText(rowsFor(cap,lv),cap).replace(/<br>/g,'; ').replace(/<[^>]+>/g,''))))]));});return tbl(rows)}
function materialDoc(mat){let x='';if(mat.title)x+=wp(mat.title,{b:true,i:true,align:'center'});if(mat.author)x+=wp(mat.author,{i:true,align:'center'});String(mat.text||'').split(/\n/).forEach(line=>x+=wp(line,{i:true,after:20}));if(mat.source)x+=wp(mat.source,{i:true,align:'right'});return x}
function questionDoc(q){let x=wpRuns([{text:`Câu ${q.number} (${fmt(q.points)} điểm): `,b:true},{text:q.prompt||''}]);if(q.form==='TNKQ'&&q.options?.length){q.options.forEach((o,i)=>x+=wp(`${String.fromCharCode(65+i)}. ${String(o).replace(/^\s*[A-D][.)]\s*/i,'')}`,{after:20}));}if(q.subtype==='truefalse'&&q.statements?.length)q.statements.forEach((s,i)=>x+=wp(`${String.fromCharCode(97+i)}) ${s.text||s}`,{after:20}));return x}
function examDoc(code){const mat=sourcePayload().read;let x=headerDoc()+wp('Họ và tên học sinh: ............................................................................................ Lớp: ....................')+wp(`PHẦN I. ĐỌC (${fmt($('#readScore').value)} điểm)`,{b:true,sz:24})+wp('Đọc văn bản và thực hiện yêu cầu bên dưới:',{b:true})+materialDoc(mat);(code.readQuestions||[]).forEach(q=>x+=questionDoc(q));x+=wp(`PHẦN II. VIẾT (${fmt($('#writeScore').value)} điểm)`,{b:true,sz:24})+wp(code.write?.prompt||'',{b:true})+wp('----- HẾT -----',{b:true,align:'center'});return x}
function markingDoc(){
  const codes=state.exam.examCodes;
  let x=headerDoc()+wp('HƯỚNG DẪN CHẤM',{b:true,align:'center',sz:26})+wp(`PHẦN I. ĐỌC (${fmt($('#readScore').value)} điểm)`,{b:true,sz:24});
  const tn=codes[0].readQuestions.filter(q=>q.form==='TNKQ');
  if(tn.length){
    const groups=new Map();tn.forEach(q=>groups.set(`${q.subtype}|${q.points}`,{subtype:q.subtype,points:q.points}));
    groups.forEach(g=>{x+=wp(`${tnName(g.subtype)}: Mỗi câu đúng được ${fmt(g.points)} điểm.`,{i:true})});
    const trows=[tr([tc(wp('Câu',{b:true,align:'center'}),{fill:'EDEBFA'}),...tn.map(q=>tc(wp(String(q.number),{b:true,align:'center'}),{fill:'EDEBFA'}))])];
    codes.forEach(c=>{const ctn=c.readQuestions.filter(q=>q.form==='TNKQ');const cc=[tc(wp(`Đề ${c.code}`,{b:true}))];ctn.forEach(q=>cc.push(tc(wp(answerText(q),{align:'center'}))));trows.push(tr(cc));});
    x+=tbl(trows);
  }
  x+=wp('II. TỰ LUẬN',{b:true});
  const tlCodes=codes.map(c=>c.readQuestions.filter(q=>q.form==='TL'));
  const max=Math.max(...tlCodes.map(a=>a.length),0);
  const rows=[tr([tc(wp('Câu',{b:true,align:'center'}),{fill:'EDEBFA'}),...codes.map(c=>tc(wp(`ĐỀ ${c.code}`,{b:true,align:'center'}),{fill:'EDEBFA'})),tc(wp('Điểm',{b:true,align:'center'}),{fill:'EDEBFA'})])];
  for(let i=0;i<max;i++){
    const qs=tlCodes.map(a=>a[i]);
    const cells=[tc(wp(String(qs.find(Boolean)?.number||''),{align:'center'}))];
    qs.forEach(q=>{
      let cell='';
      if(q){
        cell+=wp(answerText(q));
        if(q.rubric?.length){cell+=wp('Hướng dẫn chấm:',{b:true,i:true});q.rubric.forEach(r=>{cell+=wp(`– ${r.content} (${fmt(r.points)}đ)`,{i:true})});}
      }
      cells.push(tc(cell));
    });
    cells.push(tc(wp(fmt(qs.find(Boolean)?.points||0),{align:'center'})));
    rows.push(tr(cells));
  }
  x+=tbl(rows)+wp(`PHẦN II. VIẾT (${fmt($('#writeScore').value)} điểm)`,{b:true,sz:24});
  codes.forEach(c=>{
    x+=wp(`ĐỀ ${c.code}`,{b:true});
    x+=wp('HS có thể trình bày, diễn đạt theo cách riêng, miễn là hợp lí hoặc tương tự “Yêu cầu cần đạt”.',{i:true});
    x+=wp(c.write?.prompt||'',{b:true});
    (c.write?.rubric||[]).forEach(g=>{
      x+=wp(`${g.group||'Tiêu chí'}${g.points!=null?` (${fmt(g.points)} điểm)`:''}`,{b:true});
      if(g.content)x+=wp(g.content);
      (g.details||[]).forEach(d=>{x+=wp(`– ${d.content||d}${d.points!=null?` (${fmt(d.points)}đ)`:''}`)});
    });
    if(c.write?.bands?.length){x+=wp('Biểu điểm',{b:true});c.write.bands.forEach(b=>{x+=wp(`– ${b.label}: ${b.description}`)});}
  });
  return x;
}
function docXml(body){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="850" w:bottom="1134" w:left="1417" w:header="708" w:footer="708"/></w:sectPr></w:body></w:document>`}
async function exportDocx(){if(!state.exam)return alert('Chưa có đề.');if(!$('#reviewConfirm').checked)return alert('Hãy xác nhận đã kiểm tra bản cuối.');if(!window.JSZip)return alert('Thiếu JSZip.');const zip=new JSZip();zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');let body=wp('I. MỤC TIÊU ĐỀ KIỂM TRA',{b:true,sz:24})+wp(`Đánh giá năng lực Đọc và Viết môn Ngữ văn lớp ${state.grade} theo phạm vi và ma trận giáo viên đã thiết lập.`)+wp('II. HÌNH THỨC ĐỀ KIỂM TRA',{b:true,sz:24})+wp(examForm()==='mixed'?'Kết hợp trắc nghiệm khách quan và tự luận.':'Tự luận 100%.')+wp('III. THIẾT LẬP MA TRẬN, ĐẶC TẢ',{b:true,sz:24})+wp('1. Ma trận',{b:true})+matrixDoc()+wp('2. Bảng đặc tả',{b:true})+specDoc()+wp('IV. ĐỀ KIỂM TRA',{b:true,sz:24});state.exam.examCodes.forEach((c,i)=>{body+=(i?'<w:p><w:r><w:br w:type="page"/></w:r></w:p>':'')+examDoc(c)});body+='<w:p><w:r><w:br w:type="page"/></w:r></w:p>'+markingDoc();zip.folder('word').file('document.xml',docXml(body));const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);const type=String($('#examType').value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_|_$/g,'');a.download=`De_Ngu_van_${state.grade}_${type}.docx`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function bind(){if(CFG.APP_VERSION)$('#versionBadge').textContent='V'+CFG.APP_VERSION;state.grade=$('#grade').value;state.form=examForm();renderScope();syncScores();syncWriteSourceMode();syncProvider();$$('.step-btn').forEach(b=>b.addEventListener('click',()=>showStep(b.dataset.step)));$$('.next-btn').forEach(b=>b.addEventListener('click',()=>{if(validateStep(b.dataset.next))showStep(b.dataset.next)}));$$('.prev-btn').forEach(b=>b.addEventListener('click',()=>showStep(b.dataset.prev)));$('#grade').addEventListener('change',e=>{state.grade=e.target.value;resetDerived();renderScope();renderMatrix();renderSpec()});$$('input[name="examForm"]').forEach(x=>x.addEventListener('change',clearMatrixForForm));$('#readScore').addEventListener('input',()=>{syncScores();renderMatrix()});$('#writeScore').addEventListener('input',()=>{syncScores();renderMatrix()});$('#readTrack').addEventListener('change',()=>{resetDerived();renderTrackDetails();renderMatrix();renderSpec()});$('#writeTrack').addEventListener('change',()=>{resetDerived();renderTrackDetails();syncWriteSourceMode();renderMatrix();renderSpec()});$$('input[name="writeSourceMode"]').forEach(x=>x.addEventListener('change',syncWriteSourceMode));['readText','readSource','writeText','writeSource','writeRequirement','sourceConfirm'].forEach(id=>$('#'+id)?.addEventListener('input',()=>validateSources(false)));$('#sourceConfirm').addEventListener('change',()=>validateSources(false));$$('input[name="aiProvider"]').forEach(x=>x.addEventListener('change',syncProvider));$('#toggleKey').addEventListener('click',()=>$('#apiKey').type=$('#apiKey').type==='password'?'text':'password');$('#testApiBtn').addEventListener('click',testApi);$('#modelSelect').addEventListener('change',e=>state.model=e.target.value);$('#closeMatrixDialog').addEventListener('click',closeDialog);$('#cancelDialog').addEventListener('click',closeDialog);$('#addConfigBtn').addEventListener('click',()=>{const d=state.dialog;if(!d)return;d.rows.push(d.cap==='write'?{form:'TL',count:1,points:.5}:d.form==='TNKQ'?{form:'TNKQ',subtype:'single',count:1,points:.5}:{form:'TL',count:1,points:1});renderConfigRows()});$('#saveDialog').addEventListener('click',saveDialog);$('#generateBtn').addEventListener('click',generateExam);$$('.review-tab').forEach(b=>b.addEventListener('click',()=>{state.reviewTab=b.dataset.reviewTab;renderReview()}));$$('.chip-btn').forEach(b=>b.addEventListener('click',()=>$('#aiEditRequest').value=b.dataset.aiQuick||''));$('#aiEditBtn').addEventListener('click',aiEdit);$('#undoEditBtn').addEventListener('click',undoEdit);$('#aiReviewBtn').addEventListener('click',aiReview);$('#reviewConfirm').addEventListener('change',updateExportGate);$('#exportDocxBtn').addEventListener('click',exportDocx);renderMatrix();renderSpec();validateSources(false);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
